-- Main-source VLS tables required by the single-backend migration.
-- This script is idempotent and keeps the single tenant fixed by application services to 000000.

CREATE TABLE IF NOT EXISTS `vls_camera_display_setting` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(64) DEFAULT '000000',
  `device_id` bigint NOT NULL,
  `scene` varchar(64) DEFAULT NULL,
  `brightness` int DEFAULT NULL,
  `contrast` int DEFAULT NULL,
  `saturation` int DEFAULT NULL,
  `sharpness` int DEFAULT NULL,
  `exposure_mode` varchar(64) DEFAULT NULL,
  `max_shutter_limit` varchar(64) DEFAULT NULL,
  `min_shutter_limit` varchar(64) DEFAULT NULL,
  `gain_limit` int DEFAULT NULL,
  `low_light_electronic_shutter` varchar(64) DEFAULT NULL,
  `focus_mode` varchar(64) DEFAULT NULL,
  `min_focus_distance` varchar(64) DEFAULT NULL,
  `day_night_switch` varchar(64) DEFAULT NULL,
  `sensitivity` int DEFAULT NULL,
  `anti_fill_light_over_exposure` varchar(64) DEFAULT NULL,
  `infrared_lamp_mode` varchar(64) DEFAULT NULL,
  `brightness_limit` int DEFAULT NULL,
  `backlight_compensation` varchar(64) DEFAULT NULL,
  `wide_dynamic` varchar(64) DEFAULT NULL,
  `strong_light_suppression` varchar(64) DEFAULT NULL,
  `white_balance` varchar(64) DEFAULT NULL,
  `digital_noise_reduction` varchar(64) DEFAULT NULL,
  `noise_reduction_level` int DEFAULT NULL,
  `defog_mode` varchar(64) DEFAULT NULL,
  `electronic_stabilization` varchar(64) DEFAULT NULL,
  `mirror_mode` varchar(64) DEFAULT NULL,
  `pal50hz` varchar(64) DEFAULT NULL,
  `lens_initialization` varchar(64) DEFAULT NULL,
  `zoom_limit` int DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `create_user` bigint DEFAULT NULL,
  `create_dept` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_user` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `status` int DEFAULT 1,
  `is_deleted` int DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_camera_display_setting_device` (`device_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vls_camera_osd_setting` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(64) DEFAULT '000000',
  `device_id` bigint NOT NULL,
  `show_name` int DEFAULT 1,
  `show_date` int DEFAULT 1,
  `show_week` int DEFAULT 1,
  `channel_name` varchar(255) DEFAULT NULL,
  `time_format` varchar(64) DEFAULT NULL,
  `date_format` varchar(64) DEFAULT NULL,
  `overlay1_enabled` int DEFAULT 0,
  `overlay1_text` varchar(255) DEFAULT NULL,
  `overlay2_enabled` int DEFAULT 0,
  `overlay2_text` varchar(255) DEFAULT NULL,
  `overlay3_enabled` int DEFAULT 0,
  `overlay3_text` varchar(255) DEFAULT NULL,
  `osd_property` varchar(64) DEFAULT NULL,
  `osd_font` varchar(64) DEFAULT NULL,
  `osd_color` varchar(64) DEFAULT NULL,
  `align_mode` varchar(64) DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `create_user` bigint DEFAULT NULL,
  `create_dept` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_user` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `status` int DEFAULT 1,
  `is_deleted` int DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_camera_osd_setting_device` (`device_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vls_audio_anomaly_detection_setting` (
  `id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `audio_input_anomaly_enabled` int DEFAULT 0,
  `sound_rise_enabled` int DEFAULT 0,
  `sound_rise_sensitivity` int DEFAULT 50,
  `sound_intensity_threshold` int DEFAULT 50,
  `sound_drop_enabled` int DEFAULT 0,
  `sound_drop_sensitivity` int DEFAULT 50,
  `remark` varchar(500) DEFAULT NULL,
  `tenant_id` varchar(64) DEFAULT '000000',
  `create_user` bigint DEFAULT NULL,
  `create_dept` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_user` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `status` int DEFAULT 1,
  `is_deleted` int DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_audio_anomaly_device_id` (`device_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vls_audio_defense_time_setting` (
  `id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `protection_time` json DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `tenant_id` varchar(64) DEFAULT '000000',
  `create_user` bigint DEFAULT NULL,
  `create_dept` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_user` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `status` int DEFAULT 1,
  `is_deleted` int DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_audio_defense_device_id` (`device_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vls_audio_linkage_mode_setting` (
  `id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `conventional_linkage_enabled` int DEFAULT 0,
  `email_linkage_enabled` int DEFAULT 0,
  `upload_center_linkage_enabled` int DEFAULT 0,
  `alarm_output_linkage_enabled` int DEFAULT 0,
  `alarm_output_channel` varchar(255) DEFAULT NULL,
  `record_linkage_enabled` int DEFAULT 0,
  `record_channel` varchar(255) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `tenant_id` varchar(64) DEFAULT '000000',
  `create_user` bigint DEFAULT NULL,
  `create_dept` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_user` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `status` int DEFAULT 1,
  `is_deleted` int DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_audio_linkage_device_id` (`device_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vls_record_event_strategy` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(64) DEFAULT '000000',
  `create_user` bigint DEFAULT NULL,
  `create_dept` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_user` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `status` int DEFAULT 1,
  `is_deleted` int DEFAULT 0,
  `device_id` varchar(64) NOT NULL,
  `motion_detection_enabled` tinyint(1) DEFAULT 0,
  `ptz_alarm_report_enabled` tinyint(1) DEFAULT 0,
  `dynamic_analysis_enabled` tinyint(1) DEFAULT 0,
  `occlusion_alarm_enabled` tinyint(1) DEFAULT 0,
  `trigger_action` varchar(16) DEFAULT NULL,
  `pre_record_seconds` int DEFAULT 0,
  `post_record_seconds` int DEFAULT 0,
  `alarm_frequency_minutes` int DEFAULT NULL,
  `alarm_level` varchar(32) DEFAULT NULL,
  `alarm_method` varchar(255) DEFAULT NULL,
  `receiver_ids` varchar(1024) DEFAULT NULL,
  `protection_time` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_event_device_id` (`device_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vls_resource_type` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(64) DEFAULT '000000',
  `type_code` varchar(64) DEFAULT NULL,
  `type_name` varchar(128) NOT NULL,
  `is_active` tinyint DEFAULT 1,
  `sort_order` int DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `create_user` bigint DEFAULT NULL,
  `create_dept` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_user` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `status` int DEFAULT 1,
  `is_deleted` int DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_vls_resource_type_code` (`tenant_id`,`type_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vls_resource_spec` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(64) DEFAULT '000000',
  `resource_type_id` bigint NOT NULL,
  `spec_name` varchar(128) NOT NULL,
  `cpu_model` varchar(64) DEFAULT NULL,
  `vcpu` int DEFAULT NULL,
  `memory_gb` int DEFAULT NULL,
  `gpu_desc` varchar(128) DEFAULT NULL,
  `system_disk_gb` int DEFAULT NULL,
  `data_disk_gb` int DEFAULT NULL,
  `is_active` tinyint DEFAULT 1,
  `sort_order` int DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `create_user` bigint DEFAULT NULL,
  `create_dept` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_user` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `status` int DEFAULT 1,
  `is_deleted` int DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_vls_resource_spec_type` (`tenant_id`,`resource_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vls_device_tag_relation` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(64) DEFAULT '000000',
  `device_id` bigint NOT NULL,
  `tag_id` bigint NOT NULL,
  `create_user` bigint DEFAULT NULL,
  `create_dept` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_user` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `status` int DEFAULT 1,
  `is_deleted` int DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_device_tag` (`device_id`,`tag_id`),
  KEY `idx_device_tag_tag_id` (`tag_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vls_algorithm_orchestration` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(64) DEFAULT '000000',
  `orchestration_name` varchar(100) NOT NULL,
  `orchestration_desc` varchar(500) DEFAULT NULL,
  `trigger_type` varchar(20) NOT NULL DEFAULT 'realtime',
  `execute_mode` varchar(20) NOT NULL DEFAULT 'serial',
  `algorithm_steps` json NOT NULL,
  `input_config` json DEFAULT NULL,
  `output_config` json DEFAULT NULL,
  `device_count` int DEFAULT 0,
  `run_count` int DEFAULT 0,
  `orchestration_status` varchar(20) NOT NULL DEFAULT 'active',
  `last_run_time` datetime DEFAULT NULL,
  `avg_run_time` int DEFAULT NULL,
  `success_rate` decimal(5,2) DEFAULT NULL,
  `create_user` bigint DEFAULT NULL,
  `create_dept` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_user` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `status` int DEFAULT 1,
  `is_deleted` int DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vls_analysis_request` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(64) DEFAULT '000000',
  `analysis_type` varchar(255) DEFAULT NULL,
  `analysis_name` varchar(100) DEFAULT NULL,
  `device_ids` varchar(500) DEFAULT NULL,
  `region_info` varchar(255) DEFAULT NULL,
  `time_range` varchar(255) DEFAULT NULL,
  `images` text,
  `request_status` varchar(20) NOT NULL DEFAULT 'pending',
  `progress` int DEFAULT 0,
  `result_path` varchar(500) DEFAULT NULL,
  `start_time` datetime DEFAULT NULL,
  `complete_time` datetime DEFAULT NULL,
  `error_message` text,
  `description` text,
  `create_user` bigint DEFAULT NULL,
  `create_dept` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_user` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `status` int DEFAULT 1,
  `is_deleted` int DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_analysis_request_status` (`request_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vls_camera_apply_record` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(64) DEFAULT '000000',
  `create_user` bigint DEFAULT NULL,
  `create_dept` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_user` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `status` int DEFAULT 1,
  `is_deleted` int DEFAULT 0,
  `device_info_id` bigint NOT NULL,
  `apply_reason` varchar(500) NOT NULL,
  `apply_remark` varchar(500) DEFAULT NULL,
  `apply_user_name` varchar(128) NOT NULL,
  `apply_time` datetime NOT NULL,
  `apply_status` varchar(32) NOT NULL,
  `approval_comment` varchar(500) DEFAULT NULL,
  `approve_user_name` varchar(128) DEFAULT NULL,
  `approve_time` datetime DEFAULT NULL,
  `complete_remark` varchar(500) DEFAULT NULL,
  `complete_user_name` varchar(128) DEFAULT NULL,
  `complete_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_vls_camera_apply_device` (`device_info_id`),
  KEY `idx_vls_camera_apply_status` (`apply_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vls_mobile_scene_governance` (
  `id` bigint NOT NULL,
  `name` varchar(255) NOT NULL,
  `governance_mode` varchar(32) NOT NULL,
  `cycle_type` varchar(64) DEFAULT NULL,
  `interval_days` int DEFAULT NULL,
  `weekly_days` varchar(255) DEFAULT NULL,
  `monthly_days` varchar(255) DEFAULT NULL,
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `trigger_times` varchar(1024) DEFAULT NULL,
  `location_ids` varchar(1024) DEFAULT NULL,
  `algorithm_ids` varchar(1024) DEFAULT NULL,
  `camera_ids` varchar(1024) DEFAULT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `tenant_id` varchar(64) DEFAULT '000000',
  `create_user` bigint DEFAULT NULL,
  `create_dept` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_user` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `status` int DEFAULT 1,
  `is_deleted` int DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_mobile_scene_mode` (`governance_mode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vls_mobile_scene_governance_sub_task` (
  `id` bigint NOT NULL,
  `governance_id` bigint NOT NULL,
  `name` varchar(255) NOT NULL,
  `execute_time` datetime NOT NULL,
  `task_status` varchar(32) DEFAULT 'pending',
  `location_ids` varchar(1024) DEFAULT NULL,
  `algorithm_ids` varchar(1024) DEFAULT NULL,
  `camera_ids` varchar(1024) DEFAULT NULL,
  `tenant_id` varchar(64) DEFAULT '000000',
  `create_user` bigint DEFAULT NULL,
  `create_dept` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_user` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `status` int DEFAULT 1,
  `is_deleted` int DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_mobile_scene_sub_governance` (`governance_id`),
  KEY `idx_mobile_scene_sub_execute_time` (`execute_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
