-- 算法训练任务表
CREATE TABLE `algorithm_training` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '训练任务ID',
  `task_name` varchar(100) NOT NULL COMMENT '任务名称',
  `algorithm_id` bigint NOT NULL COMMENT '算法ID',
  `dataset_id` bigint DEFAULT NULL COMMENT '数据集ID',
  `train_type` varchar(50) NOT NULL COMMENT '训练类型',
  `train_status` varchar(20) NOT NULL COMMENT '训练状态：pending-等待,training-训练中,completed-完成,failed-失败',
  `progress` int DEFAULT '0' COMMENT '训练进度百分比',
  `epoch_current` int DEFAULT '0' COMMENT '当前轮次',
  `epoch_total` int DEFAULT '100' COMMENT '总轮次',
  `accuracy` decimal(5,2) DEFAULT NULL COMMENT '准确率',
  `precision_value` decimal(5,2) DEFAULT NULL COMMENT '精确率',
  `recall_value` decimal(5,2) DEFAULT NULL COMMENT '召回率',
  `map_value` decimal(5,2) DEFAULT NULL COMMENT 'mAP值',
  `loss_value` decimal(10,6) DEFAULT NULL COMMENT '损失值',
  `gpu_usage` varchar(20) DEFAULT NULL COMMENT 'GPU使用率',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `estimated_time` varchar(50) DEFAULT NULL COMMENT '预计时间',
  `model_output_path` varchar(500) DEFAULT NULL COMMENT '模型输出路径',
  `log_path` varchar(500) DEFAULT NULL COMMENT '日志路径',
  `config_params` json DEFAULT NULL COMMENT '训练参数',
  `error_message` text COMMENT '错误信息',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0-否，1-是',
  PRIMARY KEY (`id`),
  KEY `idx_algorithm_id` (`algorithm_id`),
  KEY `idx_train_status` (`train_status`),
  KEY `idx_created_time` (`created_time`)
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='算法训练任务表';

-- 插入测试数据
INSERT INTO `algorithm_training` (
  `task_name`, 
  `algorithm_id`, 
  `dataset_id`, 
  `train_type`, 
  `train_status`, 
  `progress`, 
  `epoch_current`, 
  `epoch_total`, 
  `accuracy`, 
  `precision_value`, 
  `recall_value`, 
  `map_value`, 
  `loss_value`, 
  `gpu_usage`, 
  `start_time`, 
  `end_time`, 
  `estimated_time`, 
  `model_output_path`, 
  `log_path`, 
  `config_params`, 
  `error_message`, 
  `created_by`
) VALUES
-- 完成的训练任务
(
  '人员检测模型训练-v1.0', 
  1, 
  1, 
  'object_detection', 
  'completed', 
  100, 
  100, 
  100, 
  85.67, 
  82.34, 
  88.91, 
  86.45, 
  0.123456, 
  '75%', 
  '2024-01-10 08:00:00', 
  '2024-01-10 12:30:00', 
  '4.5小时', 
  '/models/person_detection_v1.0.pth', 
  '/logs/person_detection_v1.0.log', 
  '{"batch_size": 16, "learning_rate": 0.001, "optimizer": "Adam"}', 
  NULL, 
  1
),
-- 正在训练的任务
(
  '车辆识别模型训练-v2.1', 
  2, 
  2, 
  'object_detection', 
  'training', 
  65, 
  65, 
  100, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  0.234567, 
  '82%', 
  '2024-01-15 14:20:00', 
  NULL, 
  '预计还需2小时', 
  '/models/vehicle_detection_v2.1.pth', 
  '/logs/vehicle_detection_v2.1.log', 
  '{"batch_size": 32, "learning_rate": 0.0005, "optimizer": "SGD"}', 
  NULL, 
  1
),
-- 等待中的任务
(
  '人脸识别模型训练-v1.5', 
  3, 
  3, 
  'face_recognition', 
  'pending', 
  0, 
  0, 
  200, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  '预计6小时', 
  '/models/face_recognition_v1.5.pth', 
  '/logs/face_recognition_v1.5.log', 
  '{"batch_size": 64, "learning_rate": 0.002, "optimizer": "Adam"}', 
  NULL, 
  1
),
-- 失败的任务
(
  '姿态识别模型训练-v1.0', 
  4, 
  4, 
  'pose_estimation', 
  'failed', 
  45, 
  45, 
  100, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  0.456789, 
  '60%', 
  '2024-01-12 10:00:00', 
  '2024-01-12 13:15:00', 
  NULL, 
  NULL, 
  '/logs/pose_estimation_v1.0.log', 
  '{"batch_size": 24, "learning_rate": 0.001, "optimizer": "Adam"}', 
  'CUDA out of memory', 
  1
),
-- 更多测试数据
(
  '目标跟踪模型训练-v1.2', 
  5, 
  5, 
  'object_tracking', 
  'completed', 
  100, 
  150, 
  150, 
  91.23, 
  89.67, 
  92.45, 
  90.88, 
  0.087654, 
  '88%', 
  '2024-01-08 09:30:00', 
  '2024-01-08 18:45:00', 
  '9.25小时', 
  '/models/object_tracking_v1.2.pth', 
  '/logs/object_tracking_v1.2.log', 
  '{"batch_size": 8, "learning_rate": 0.0001, "optimizer": "AdamW"}', 
  NULL, 
  1
),
(
  '语义分割模型训练-v2.0', 
  6, 
  6, 
  'semantic_segmentation', 
  'pending', 
  0, 
  0, 
  80, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  '预计5小时', 
  '/models/semantic_segmentation_v2.0.pth', 
  '/logs/semantic_segmentation_v2.0.log', 
  '{"batch_size": 12, "learning_rate": 0.0008, "optimizer": "Adam"}', 
  NULL, 
  1
),
(
  '图像分类模型训练-v3.1', 
  7, 
  7, 
  'image_classification', 
  'training', 
  78, 
  78, 
  100, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  0.178923, 
  '91%', 
  '2024-01-16 11:00:00', 
  NULL, 
  '预计还需1.5小时', 
  '/models/image_classification_v3.1.pth', 
  '/logs/image_classification_v3.1.log', 
  '{"batch_size": 128, "learning_rate": 0.003, "optimizer": "SGD"}', 
  NULL, 
  1
),
(
  '文本检测模型训练-v1.8', 
  8, 
  8, 
  'text_detection', 
  'completed', 
  100, 
  120, 
  120, 
  87.34, 
  85.12, 
  89.67, 
  87.89, 
  0.165432, 
  '79%', 
  '2024-01-05 16:20:00', 
  '2024-01-06 02:10:00', 
  '9.83小时', 
  '/models/text_detection_v1.8.pth', 
  '/logs/text_detection_v1.8.log', 
  '{"batch_size": 20, "learning_rate": 0.0015, "optimizer": "Adam"}', 
  NULL, 
  1
),
(
  '行为识别模型训练-v1.0', 
  9, 
  9, 
  'action_recognition', 
  'failed', 
  23, 
  23, 
  100, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  0.789012, 
  '45%', 
  '2024-01-14 07:45:00', 
  '2024-01-14 10:30:00', 
  NULL, 
  NULL, 
  '/logs/action_recognition_v1.0.log', 
  '{"batch_size": 16, "learning_rate": 0.001, "optimizer": "Adam"}', 
  '数据集损坏', 
  1
),
(
  '异常检测模型训练-v2.3', 
  10, 
  10, 
  'anomaly_detection', 
  'pending', 
  0, 
  0, 
  250, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  '预计12小时', 
  '/models/anomaly_detection_v2.3.pth', 
  '/logs/anomaly_detection_v2.3.log', 
  '{"batch_size": 32, "learning_rate": 0.0002, "optimizer": "AdamW"}', 
  NULL, 
  1
);

-- 创建相关索引以优化查询性能
CREATE INDEX idx_algorithm_training_algorithm_id ON algorithm_training(algorithm_id);
CREATE INDEX idx_algorithm_training_dataset_id ON algorithm_training(dataset_id);
CREATE INDEX idx_algorithm_training_train_status ON algorithm_training(train_status);
CREATE INDEX idx_algorithm_training_created_time ON algorithm_training(created_time);
CREATE INDEX idx_algorithm_training_start_time ON algorithm_training(start_time);
CREATE INDEX idx_algorithm_training_created_by ON algorithm_training(created_by);
CREATE INDEX idx_algorithm_training_train_type ON algorithm_training(train_type);

-- 创建复合索引以优化常见查询
CREATE INDEX idx_algorithm_training_status_time ON algorithm_training(train_status, created_time);
CREATE INDEX idx_algorithm_training_algorithm_status ON algorithm_training(algorithm_id, train_status);
CREATE INDEX idx_algorithm_training_dataset_status ON algorithm_training(dataset_id, train_status);

-- 添加表注释
ALTER TABLE algorithm_training COMMENT = '算法训练任务表，用于管理AI算法的训练任务，包括训练状态、进度、性能指标等信息'; 