CREATE TABLE vls_compute_node (
    id BIGINT NOT NULL PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    provider VARCHAR(32) NOT NULL DEFAULT 'autodl',
    host VARCHAR(253) NOT NULL,
    port INT NOT NULL,
    username VARCHAR(64) NOT NULL,
    password_cipher TEXT NOT NULL,
    host_key TEXT NULL,
    python_path VARCHAR(500) NOT NULL,
    work_dir VARCHAR(500) NOT NULL,
    gpu_index INT NOT NULL DEFAULT 0,
    enabled TINYINT NOT NULL DEFAULT 1,
    probe_state VARCHAR(20) NOT NULL DEFAULT 'UNTESTED',
    probe_json TEXT NULL,
    probe_time DATETIME NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_compute_endpoint (host, port, username),
    INDEX idx_compute_tenant (tenant_id, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE vls_cloud_training_job (
    id CHAR(36) NOT NULL PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    training_id BIGINT NOT NULL,
    node_id BIGINT NOT NULL,
    container_record_id BIGINT NOT NULL,
    dataset_id BIGINT NOT NULL,
    version_id BIGINT NOT NULL,
    annotation_type VARCHAR(32) NOT NULL,
    snapshot_json LONGTEXT NOT NULL,
    base_model VARCHAR(2048) NOT NULL,
    options_json TEXT NOT NULL,
    run_dir VARCHAR(1024) NOT NULL,
    job_state VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
    cancel_requested TINYINT NOT NULL DEFAULT 0,
    progress INT NOT NULL DEFAULT 0,
    epoch_current INT NOT NULL DEFAULT 0,
    message VARCHAR(500) NULL,
    log_tail MEDIUMTEXT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_cloud_node_queue (node_id, job_state, create_time),
    INDEX idx_cloud_training (tenant_id, training_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
