CREATE TABLE IF NOT EXISTS `vls_llm_provider` (
    `id` bigint NOT NULL COMMENT 'Primary key',
    `tenant_id` varchar(64) NOT NULL COMMENT 'Owning tenant',
    `name` varchar(100) NOT NULL COMMENT 'Display name',
    `base_url` varchar(500) NOT NULL COMMENT 'OpenAI-compatible API base URL',
    `model_name` varchar(200) NOT NULL COMMENT 'Vision model name',
    `api_key_ciphertext` text NOT NULL COMMENT 'Encrypted API key',
    `timeout_seconds` int NOT NULL DEFAULT 30 COMMENT 'Request timeout in seconds',
    `enabled` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Whether provider is enabled',
    `create_user` varchar(64) NULL,
    `create_dept` varchar(64) NULL,
    `create_time` datetime NULL,
    `update_user` varchar(64) NULL,
    `update_time` datetime NULL,
    `status` int NOT NULL DEFAULT 1,
    `is_deleted` int NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_vls_llm_provider_tenant_name` (`tenant_id`, `name`, `is_deleted`),
    KEY `idx_vls_llm_provider_tenant_enabled` (`tenant_id`, `enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='OpenAI-compatible vision model providers';

CREATE TABLE IF NOT EXISTS `vls_algorithm_llm_review_config` (
    `id` bigint NOT NULL COMMENT 'Primary key',
    `tenant_id` varchar(64) NOT NULL COMMENT 'Owning tenant',
    `algorithm_id` bigint NOT NULL COMMENT 'VLS algorithm ID',
    `provider_id` bigint NULL COMMENT 'Vision provider ID',
    `enabled` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Whether LLM review is enabled',
    `prompt_template` text NULL COMMENT 'Review prompt template',
    `decision_threshold` decimal(5,4) NOT NULL DEFAULT 0.8000 COMMENT 'Automatic decision threshold',
    `max_retries` int NOT NULL DEFAULT 2 COMMENT 'Retry count after the first attempt',
    `failure_strategy` varchar(30) NOT NULL DEFAULT 'MANUAL_REVIEW' COMMENT 'Failure handling strategy',
    `image_mode` varchar(30) NOT NULL DEFAULT 'FULL_AND_CROP' COMMENT 'FULL, CROP, or FULL_AND_CROP',
    `create_user` varchar(64) NULL,
    `create_dept` varchar(64) NULL,
    `create_time` datetime NULL,
    `update_user` varchar(64) NULL,
    `update_time` datetime NULL,
    `status` int NOT NULL DEFAULT 1,
    `is_deleted` int NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_vls_algorithm_llm_review` (`tenant_id`, `algorithm_id`, `is_deleted`),
    KEY `idx_vls_algorithm_llm_provider` (`tenant_id`, `provider_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Algorithm-level LLM review configuration';

CREATE TABLE IF NOT EXISTS `vls_llm_review_task` (
    `id` bigint NOT NULL COMMENT 'Primary key',
    `tenant_id` varchar(64) NOT NULL COMMENT 'Owning tenant',
    `source_message_id` varchar(64) NOT NULL COMMENT 'MQTT message ID',
    `device_event_id` varchar(64) NOT NULL COMMENT 'Device event ID',
    `device_id` varchar(100) NOT NULL COMMENT 'Device business ID',
    `algorithm_id` bigint NOT NULL COMMENT 'VLS algorithm ID',
    `provider_id` bigint NOT NULL COMMENT 'Vision provider ID',
    `media_id` varchar(64) NOT NULL COMMENT 'Event image media ID',
    `event_payload_json` longtext NOT NULL COMMENT 'Validated event snapshot',
    `config_snapshot_json` longtext NOT NULL COMMENT 'Review configuration snapshot',
    `review_status` varchar(30) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/PROCESSING/RETRY/CONFIRMED/REJECTED/MANUAL_REVIEW/ERROR',
    `attempt_count` int NOT NULL DEFAULT 0,
    `next_retry_time` datetime NOT NULL,
    `locked_by` varchar(64) NULL,
    `locked_at` datetime NULL,
    `decision` varchar(30) NULL,
    `confidence` decimal(5,4) NULL,
    `reason` varchar(1000) NULL,
    `raw_response` text NULL,
    `last_error` varchar(2000) NULL,
    `formal_event_id` varchar(100) NULL COMMENT 'Created active-safety event ID',
    `reviewed_by` varchar(64) NULL,
    `reviewed_at` datetime NULL,
    `create_time` datetime NOT NULL,
    `update_time` datetime NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_vls_llm_review_message` (`tenant_id`, `source_message_id`),
    UNIQUE KEY `uk_vls_llm_review_device_event` (`tenant_id`, `device_id`, `device_event_id`),
    KEY `idx_vls_llm_review_scan` (`review_status`, `next_retry_time`),
    KEY `idx_vls_llm_review_tenant_status` (`tenant_id`, `review_status`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Durable LLM event review task';
