import org.springblade.core.tool.utils.DigestUtil;

/**
 * HashHelper utility to print the database password hash generated by DigestUtil.encrypt
 */
public class HashHelper {
    public static void main(String[] args) {
        String password = args.length > 0 ? args[0] : "admin";
        System.out.println("Password: " + password);
        System.out.println("DigestUtil.encrypt: " + DigestUtil.encrypt(password));
    }
}
