# -*- coding: utf-8 -*-
import os
import sys

# Ensure stdout uses utf-8
if sys.version_info >= (3, 0):
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')

translations = {
    "根据实例名称查询容器实例（用于重名检查）": "Query container instance by instance name (used for duplicate name check)",
    "根据容器ID查询容器实例": "Query container instance by container ID",
    "根据录像ID播放本地文件，支持Range": "Play local file by recording ID, support Range",
    "根据数据集ID删除所有图片 (兼容旧接口，实际使用annotation_id)": "Delete all images by dataset ID (compatible with old interface, actually uses annotation_id)",
    "根据数据集ID查询图片列表 (兼容旧接口，实际使用annotation_id)": "Query image list by dataset ID (compatible with old interface, actually uses annotation_id)",
    "根据数据集ID查询训练任务列表": "Query training task list by dataset ID",
    "根据数据集ID获取图片列表": "Get image list by dataset ID",
    "根据标注状态查询标注列表": "Query annotation list by annotation status",
    "根据标注状态查询标注列表：{}": "Query annotation list by annotation status: {}",
    "根据标注状态查询算法标注列表": "Query algorithm annotation list by annotation status",
    "根据标注类型查询标注列表": "Query annotation list by annotation type",
    "根据标注类型查询标注列表：{}": "Query annotation list by annotation type: {}",
    "根据标注类型查询算法标注列表": "Query algorithm annotation list by annotation type",
    "根据标注项目ID和图片名称查询标注实例": "Query annotation instance by annotation project ID and image name",
    "根据标注项目ID和标签ID查询标注实例": "Query annotation instance by annotation project ID and tag ID",
    "根据标注项目ID查询图片列表": "Query image list by annotation project ID",
    "根据标注项目ID查询所有标注实例": "Query all annotation instances by annotation project ID",
    "根据标注项目ID查询标签列表（包含使用次数统计）": "Query tag list by annotation project ID (including usage count statistics)",
    "根据标注项目ID获取图片列表": "Get image list by annotation project ID",
    "根据标签ID删除所有相关的设备标签关联": "Delete all related device tag associations by tag ID",
    "根据标签ID统计使用次数": "Count usage frequency by tag ID",
    "根据标签ID获取设备列表": "Get device list by tag ID",
    "根据标签ID获取设备标签关联列表（用于TagManagementServiceImpl兼容）": "Get device tag association list by tag ID (used for TagManagementServiceImpl compatibility)",
    "根据标签查询设备列表（实际查询device_type字段）": "Query device list by tag (actually queries device_type field)",
    "根据标签类型获取设备列表": "Get device list by tag type",
    "根据父级ID获取子标签": "Get sub-tags by parent ID",
    "根据状态查询场景治理列表": "Query scene governance list by status",
    "根据状态查询容器实例列表": "Query container instance list by status",
    "根据状态查询模型列表": "Query model list by status",
    "根据状态查询模型列表失败": "Failed to query model list by status",
    "根据状态查询模型列表失败：": "Failed to query model list by status:",
    "根据状态查询设备列表": "Query device list by status",
    "根据状态统计图片数量 (兼容旧接口，实际使用annotation_id)": "Count image quantity by status (compatible with old interface, actually uses annotation_id)",
    "根据状态获取设备列表": "Get device list by status",
    "根据算法ID和版本查询模型": "Query model by algorithm ID and version",
    "根据算法ID和版本查询模型失败": "Failed to query model by algorithm ID and version",
    "根据算法ID和版本查询模型失败：": "Failed to query model by algorithm ID and version:",
    "根据算法ID查询容器实例列表": "Query container instance list by algorithm ID",
    "根据算法ID查询模型列表": "Query model list by algorithm ID",
    "根据算法ID查询模型列表失败": "Failed to query model list by algorithm ID",
    "根据算法ID查询模型列表失败：": "Failed to query model list by algorithm ID:",
    "根据算法ID查询训练任务列表": "Query training task list by algorithm ID",
    "根据类型查询算法仓库": "Query algorithm repository by type",
    "根据类型查询算法仓库：{}": "Query algorithm repository by type: {}",
    "根据类型获取标签树": "Get tag tree by type",
    "根据角色ID获取角色菜单": "Get role menus by role ID",
    "根据训练任务ID查询模型列表": "Query model list by training task ID",
    "根据训练任务ID查询模型列表失败": "Failed to query model list by training task ID",
    "根据训练任务ID查询模型列表失败：": "Failed to query model list by training task ID:",
    "根据设备ID删除时间策略": "Delete time policy by device ID",
    "根据设备ID获取时间策略": "Get time policy by device ID",
    "根据设备ID获取标签信息": "Get tag information by device ID",
    "根据设备类型查询设备列表": "Query device list by device type",
    "根据设备类型获取设备列表": "Get device list by device type",
    "根据设备编号删除事件策略": "Delete event policy by device number",
    "根据设备编号查询设备信息": "Query device info by device number",
    "根据设备编号获取事件策略": "Get event policy by device number",
    "根据进度计算标注状态": "Calculate annotation status by progress",
    "根据顶部菜单ID获取菜单": "Get menu by top menu ID",
    "根级": "Root level",
    "格式化文件大小": "Format file size",
    "检查IP锁定": "Check IP lock",
    "检查同一仓库下名称是否重复": "Check if name is duplicated under the same repository",
    "检查同一标注项目下是否存在相同名称的其他标签": "Check if another tag with the same name exists under the same annotation project",
    "检查同一标注项目下是否存在相同名称的标签": "Check if a tag with the same name exists under the same annotation project",
    "检查名称是否重复": "Check if name is duplicated",
    "检查实例名称是否重复": "Check if instance name is duplicated",
    "检查所有模型是否可以删除": "Check if all models can be deleted",
    "检查所有模型是否可以发布": "Check if all models can be published",
    "检查是否为基础预置算法库（不允许修改某些字段）": "Check if it is a basic preset algorithm library (modification of certain fields is not allowed)",
    "检查是否为基础预置算法库（不允许删除）": "Check if it is a basic preset algorithm library (deletion is not allowed)",
    "检查是否可以删除": "Check if deletion is allowed",
    "检查是否已存在该设备的时间策略": "Check if a time policy already exists for this device",
    "检查是否有标注实例使用该标签": "Check if any annotation instance uses this tag",
    "检查是否有运行中的实例": "Check if there are running instances",
    "检查标注名称是否重复": "Check if annotation name is duplicated",
    "检查标签名称失败": "Failed to check tag name",
    "检查标签名称失败: ": "Failed to check tag name: ",
    "检查标签名称失败:  ": "Failed to check tag name:  ",
    "检查标签名称是否存在（同级别下）": "Check if tag name exists (under the same level)",
    "检查标签名称是否重复（同级别下）": "Check if tag name is duplicated (under the same level)",
    "检查标签是否存在且有效": "Check if tag exists and is valid",
    "检查模型名称和版本失败": "Failed to check model name and version",
    "检查模型名称和版本失败：": "Failed to check model name and version:",
    "检查模型名称和版本是否存在": "Check if model name and version exist",
    "检查模型是否可以下载": "Check if model can be downloaded",
    "检查模型是否可以删除": "Check if model can be deleted",
    "检查模型是否可以发布": "Check if model can be published",
    "检查模型是否可以部署": "Check if model can be deployed",
    "检查模型是否存在": "Check if model exists",
    "检查模型是否已发布": "Check if model is already published",
    "检查设备是否存在": "Check if device exists",
    "检查设备是否已有指定标签": "Check if device already has the specified tag",
    "检查设备是否有指定标签": "Check if device has the specified tag",
    "检查设备编号是否存在": "Check if device number exists",
    "检查设备编号是否已存在": "Check if device number already exists",
    "检查账号和IP是否被锁定": "Check if account and IP are locked",
    "检查账号锁定": "Check account lock",
    "检查远程服务器上的conda安装情况": "Check conda installation status on remote server",
    "检测会话通用工具：提供截图复制与资源静默关闭等辅助能力。": "General detection session tool: provides auxiliary capabilities such as screenshot copying and silent closing of resources.",
    "检测启动触发器基类：应用启动时触发一次检测任务刷新。": "Detection start trigger base class: triggers a detection task refresh once when the application starts.",
    "检测时间: {}": "Detection time: {}",
    "检测结果: {}": "Detection result: {}",
    "检测结果被过滤: deviceId={}, deviceName={}, rawSize={}, brightness={}, minScore={}": "Detection result filtered: deviceId={}, deviceName={}, rawSize={}, brightness={}, minScore={}",
    "模块名": "Module name",
    "模块名称": "Module name",
    "模型 ": "Model ",
    "模型  ": "Model  ",
    "模型ID": "Model ID",
    "模型下载路径": "Model download path",
    "模型不存在": "Model does not exist",
    "模型准确率": "Model accuracy",
    "模型名称": "Model name",
    "模型处理失败: {}": "Model processing failed: {}",
    "模型大小": "Model size",
    "模型已就绪，路径: {}": "Model is ready, path: {}",
    "模型描述": "Model description",
    "模型文件下载成功: {}": "Model file downloaded successfully: {}",
    "模型文件不存在": "Model file does not exist",
    "模型文件不存在: {}": "Model file does not exist: {}",
    "模型文件不存在，无法发布": "Model file does not exist, cannot be published",
    "模型文件路径": "Model file path",
    "模型未发布，无法下载": "Model not published, cannot be downloaded",
    "模型未发布，无法撤销": "Model not published, cannot be retracted",
    "模型未发布，无法部署": "Model not published, cannot be deployed",
    "模型格式": "Model format",
    "模型格式：ONNX,PyTorch,TensorFlow": "Model format: ONNX, PyTorch, TensorFlow",
    "模型版本": "Model version",
    "模型状态不允许发布": "Model status does not allow publishing",
    "模型训练: id={}": "Model training: id={}",
    "模型训练ID": "Model training ID",
    "模型路径不能为空": "Model path cannot be empty",
    "模型路径更新失败: id={}, onnxPath={}, rknnPath={}, int8RknnPath={}": "Model path update failed: id={}, onnxPath={}, rknnPath={}, int8RknnPath={}",
    "模型路径更新成功: id={}, onnxPath={}, rknnPath={}, int8RknnPath={}": "Model path update succeeded: id={}, onnxPath={}, rknnPath={}, int8RknnPath={}",
    "模型转换异常: id={}, error={}": "Model conversion exception: id={}, error={}",
    "模型转换异常: id={}, format={}": "Model conversion exception: id={}, format={}",
    "模型转换异常: id={}, format={}, error={}": "Model conversion exception: id={}, format={}, error={}",
    "模型转换成功": "Model conversion succeeded",
    "模型输出路径": "Model output path",
    "模拟状态刷新": "Simulated status refresh",
    "模拟算法评估过程": "Simulate algorithm evaluation process",
    "模拟部署过程": "Simulate deployment process",
    "每周执行日(1-7,逗号分隔)": "Weekly execution days (1-7, comma-separated)",
    "每周模式的时间段，JSON对象格式：{\"monday\":[0,1,2],\"tuesday\":[3,4,5]}": "Time periods in weekly mode, JSON object format: {\"monday\":[0,1,2],\"tuesday\":[3,4,5]}",
    "每天": "Everyday",
    "每天模式的时间段，JSON数组格式：[0,1,2,3]": "Time periods in daily mode, JSON array format: [0,1,2,3]",
    "每月执行日(1-31,逗号分隔)": "Monthly execution days (1-31, comma-separated)",
    "没有可删除的算法仓库": "No algorithm repositories can be deleted",
    "治理名称": "Governance name",
    "治理名称不能为空": "Governance name cannot be empty",
    "治理模式(immediate/loop)": "Governance mode (immediate/loop)",
    "注册用户": "Registered user",
    "活跃用户": "Active user",
    "流地址": "Stream address",
    "流转换配置": "Stream conversion configuration",
    "测试SFTP连接": "Test SFTP connection",
    "测试SSH连接": "Test SSH connection",
    "测试设备连接": "Test device connection",
    "测试设备连接: {}": "Test device connection: {}",
    "消息": "Message",
    "添加Token过期时间": "Add Token expiration time",
    "添加时间戳确保唯一性": "Add timestamp to ensure uniqueness",
    "添加构成JWT的类": "Add classes constituting JWT",
    "添加设备标签": "Add device tag",
    "添加设备标签失败: deviceId={}, tagIds={}": "Failed to add device tag: deviceId={}, tagIds={}",
    "添加设备标签成功: deviceId={}, newTagIds={}": "Added device tag successfully: deviceId={}, newTagIds={}",
    "添加设备标签（追加到现有标签）": "Add device tag (append to existing tags)",
    "清理base64内容，移除可能的换行符和其他字符": "Clean base64 content, removing possible line breaks and other characters",
    "清空发布时间": "Clear publish time",
    "清除IP登录失败缓存": "Clear IP login failure cache",
    "清除设备标签失败: deviceId={}": "Failed to clear device tag: deviceId={}",
    "清除设备标签成功: deviceId={}, deleted={}": "Cleared device tag successfully: deviceId={}, deleted={}",
    "清除设备的所有标签": "Clear all tags of the device",
    "清除账号登录失败缓存": "Clear account login failure cache",
    "源文件路径": "Source file path",
    "源文件路径:/upload/2024/04/01/audio.mp3": "Source file path: /upload/2024/04/01/audio.mp3",
    "源设备不存在": "Source device does not exist",
    "源设备无标签，无需复制: sourceDeviceId={}": "Source device has no tags, no copy needed: sourceDeviceId={}",
    "灵敏度": "Sensitivity",
    "点播url": "On-demand URL",
    "父主键": "Parent primary key",
    "父区划编号": "Parent division code",
    "父级ID，level=1时为NULL，level=2时为标签类型ID": "Parent ID, NULL when level=1, tag type ID when level=2",
    "父级菜单": "Parent menu",
    "父节点ID": "Parent node ID",
    "父节点不可选择自身!": "Parent node cannot be itself!",
    "父节点名称": "Parent node name",
    "状态": "Status",
    "状态 0\\": "Status 0\\",
    "状态 0草稿 1测试中 2已发布": "Status (0: Draft, 1: Testing, 2: Published)",
    "状态(0:禁用 1:启用)": "Status (0: Disabled, 1: Enabled)",
    "状态刷新失败: ": "Status refresh failed: ",
    "状态刷新成功": "Status refresh succeeded",
    "状态和类型复合索引": "Status and type composite index",
    "状态更新失败": "Status update failed",
    "状态更新异常：": "Status update exception: ",
    "状态更新成功": "Status update succeeded",
    "状态统计内部类": "Status statistics inner class",
    "状态：active-活跃,inactive-非活跃,draft-草稿": "Status: active-active, inactive-inactive, draft-draft",
    "环境变量配置": "Environment variable configuration",
    "现在的web项目几乎都会用到spring框架，而要使用spring难免需要配置大量的xml配置文件，而 springboot的出现解   决了这一问题，一个项目甚至不用部署到服务器上直接开跑，真像springboot所说：“just run”。": "Nowadays, web projects almost always use the Spring framework. To use Spring, it is inevitable to configure a large number of XML configuration files. The emergence of Spring Boot solves this problem. A project does not even need to be deployed to a server to run directly. It is truly as Spring Boot says: \"just run\".",
    "球机": "PTZ camera",
    "生成并上传数据集 YAML": "Generate and upload dataset YAML",
    "生成数据集文件内容": "Generate dataset file content",
    "生成数据集文件名": "Generate dataset file name",
    "生成数据集文件名：originalName={}, cleanName={}, datasetFileName={}": "Generate dataset file name: originalName={}, cleanName={}, datasetFileName={}",
    "生成日志文件": "Generate log file",
    "生成签名密钥": "Generate signature key",
    "生成视频缩略图失败，ffmpeg退出码异常: videoPath={}, exitCode={}": "Failed to generate video thumbnail, abnormal ffmpeg exit code: videoPath={}, exitCode={}",
    "生成视频缩略图失败，缩略图文件不存在或大小为0: videoPath={}, thumbnailPath={}": "Failed to generate video thumbnail, thumbnail file does not exist or size is 0: videoPath={}, thumbnailPath={}",
    "生成视频缩略图异常: videoPath={}, thumbnailPath={}": "Exception generating video thumbnail: videoPath={}, thumbnailPath={}",
    "生成视频缩略图被中断: videoPath={}": "Generation of video thumbnail interrupted: videoPath={}",
    "生成视频缩略图超时: videoPath={}": "Generation of video thumbnail timed out: videoPath={}",
    "生日": "Birthday",
    "用户": "User",
    "用户ID": "User ID",
    "用户service": "User service",
    "用户不存在!": "User does not exist!",
    "用户主键": "User primary key",
    "用户代理": "User agent",
    "用户信息": "User info",
    "用户修改自身信息强制忽略角色、部门、账号等字段": "Mandatory ignore of role, department, account and other fields when users modify their own info",
    "用户修改自身信息强制指定当前请求账号的ID": "Mandatory specify ID of the current request account when users modify their own info",
    "用户列表": "User list",
    "用户博客": "User blog",
    "用户同步请求DTO": "User synchronization request DTO",
    "用户名": "Username",
    "用户名或密码错误": "Incorrect username or password",
    "用户基础信息": "User basic info",
    "用户备注（各平台中的用户个人介绍）": "User remarks (user personal profile across platforms)",
    "用户头像": "User avatar",
    "用户姓名": "User full name",
    "用户授权认证": "User authorization authentication",
    "用户数据导出": "User data export",
    "用户数据模板": "User data template",
    "用户数据表": "User data table",
    "用户昵称": "User nickname",
    "用户来源": "User source",
    "用户登录失败, 账号:{}, IP:{}": "User login failed, account: {}, IP: {}",
    "用户登录失败次数过多": "Too many failed user login attempts",
    "用户登录失败次数过多，请稍后再试": "Too many failed user login attempts, please try again later",
    "用户类型枚举": "User type enum",
    "用户编号": "User number",
    "用户网址": "User website",
    "用户表": "User table",
    "用户表接口": "User table interface",
    "用户解锁": "User unlock",
    "用户邮箱": "User email",
    "申请": "Application",
    "申请ID": "Application ID",
    "申请不存在": "Application does not exist",
    "申请人": "Applicant",
    "申请人不能为空": "Applicant cannot be empty",
    "申请原因": "Application reason",
    "申请原因不能为空": "Application reason cannot be empty",
    "申请备注": "Application remarks",
    "申请时间": "Application time",
    "申请状态": "Application status",
    "申请记录ID": "Application record ID",
    "申请记录ID不能为空": "Application record ID cannot be empty",
    "申请记录不存在": "Application record does not exist",
    "电子防抖": "EIS",
    "登出": "Logout",
    "登出预留逻辑": "Logout reserved logic",
    "登录IP": "Login IP",
    "登录响应DTO": "Login response DTO",
    "登录失败key": "Login failure key",
    "登录密码": "Login password",
    "登录时间": "Login time",
    "登录用户名": "Login username",
    "登录类型": "Login type",
    "登录请求DTO": "Login request DTO",
    "登录账号": "Login account",
    "白平衡": "White balance",
    "目录不存在，创建它": "Directory does not exist, creating it",
    "目录已存在：{}": "Directory already exists: {}",
    "目标检测": "Object detection",
    "目标检测事件已创建: deviceId={}, deviceName={}, algorithmId={}, detections={}": "Object detection event created: deviceId={}, deviceName={}, algorithmId={}, detections={}",
    "目标检测启动触发器：应用启动时触发一次目标检测任务刷新。": "Object detection start trigger: triggers an object detection task refresh once when the application starts.",
    "目标检测截图已保存: deviceId={}, deviceName={}, time={}, path={}": "Object detection screenshot saved: deviceId={}, deviceName={}, time={}, path={}",
    "目标检测算法": "Object detection algorithm",
    "目标检测视频流断开: deviceId={}, deviceName={}, algorithmId={}": "Object detection video stream disconnected: deviceId={}, deviceName={}, algorithmId={}",
    "目标检测视频流结束: deviceId={}, deviceName={}, algorithmId={}": "Object detection video stream ended: deviceId={}, deviceName={}, algorithmId={}",
    "目标设备不存在: ": "Target device does not exist: ",
    "相对路径，基于当前工作目录": "Relative path, based on current working directory",
    "省级区划编号": "Provincial division code",
    "省级名称": "Provincial name",
    "真名": "Real name",
    "矩形": "Rectangle",
    "确保子目录存在：{}": "Ensure sub-directory exists: {}",
    "示例数据": "Sample data",
    "祖区划编号": "Ancestor division code",
    "祖级列表": "Ancestor list",
    "祖级机构主键": "Ancestor organization primary key",
    "离线": "Offline",
    "租户ID": "Tenant ID",
    "租户id": "Tenant ID",
    "租户信息错误!": "Tenant information error!",
    "租户名称": "Tenant name",
    "租户短语": "Tenant phrase",
    "租户管理": "Tenant management",
    "租户编号": "Tenant number",
    "租户请求DTO": "Tenant request DTO",
    "移动标签失败": "Failed to move tag",
    "移动标签失败: ": "Failed to move tag: ",
    "移动标签失败，ID: {}": "Failed to move tag, ID: {}",
    "移动标签（调整父级或排序）": "Move tag (adjust parent or sort order)",
    "移动端场景治理": "Mobile scene governance",
    "移动端场景治理 控制器": "Mobile scene governance controller",
    "移动端场景治理主任务表 Mapper 接口": "Mobile scene governance main task table Mapper interface",
    "移动端场景治理主任务表 实体类": "Mobile scene governance main task table entity class",
    "移动端场景治理主任务表 服务实现类": "Mobile scene governance main task table service implementation class",
    "移动端场景治理主任务表 服务类": "Mobile scene governance main task table service class",
    "移动端场景治理子循环任务表 Mapper 接口": "Mobile scene governance sub-loop task table Mapper interface",
    "移动端场景治理子循环任务表 实体类": "Mobile scene governance sub-loop task table entity class",
    "移动端场景治理接口": "Mobile scene governance interface",
    "移动端循环治理视图对象": "Mobile loop governance view object",
    "移除特殊字符，只保留字母、数字和下划线": "Remove special characters, keeping only letters, numbers, and underscores",
    "移除设备标签": "Remove device tag",
    "移除设备标签失败: deviceId={}, tagIds={}": "Failed to remove device tag: deviceId={}, tagIds={}",
    "移除设备标签成功: deviceId={}, tagIds={}, deleted={}": "Removed device tag successfully: deviceId={}, tagIds={}, deleted={}",
    "立即停止全部检测会话。": "Stop all detection sessions immediately.",
    "立即停止指定设备集合对应的检测会话。": "Stop detection sessions corresponding to the specified device set immediately.",
    "立即按指定设备集合刷新会话（仅保留这些设备对应的检测会话）。": "Refresh sessions by the specified device set immediately (only keeping the detection sessions corresponding to these devices).",
    "端口号": "Port number",
    "端口配置": "Port configuration",
    "第三方授权id": "Third-party authorization ID",
    "第三方注册用户": "Third-party registered user",
    "第三方登陆": "Third-party login",
    "第三方登陆信息错误!": "Third-party login information error!",
    "第三方登陆端点": "Third-party login endpoint",
    "第三方登陆配置": "Third-party login configuration",
    "第三方系统ID": "Third-party system ID",
    "第三方系统用户ID": "Third-party system user ID",
    "等待": "Wait",
    "等待命令执行完成": "Wait for command execution to complete",
    "策略类型：everyday-每天, weekly-每周": "Policy type: everyday-daily, weekly-weekly",
    "策略配置": "Policy configuration",
    "筛选匹配角色对应的权限菜单（交集）": "Filter menu permissions corresponding to matching roles (intersection)",
    "签名校验": "Signature verification",
    "简单的JSON格式转换，避免引入Jackson依赖": "Simple JSON format conversion to avoid introducing Jackson dependency",
    "算法: ": "Algorithm: ",
    "算法ID": "Algorithm ID",
    "算法ID列表，逗号分隔": "Algorithm ID list, comma-separated",
    "算法ID集合(逗号分隔)": "Algorithm ID set (comma-separated)",
    "算法id": "Algorithm ID",
    "算法下发失败，MQTT主题仅允许 oortcloud/#: topic={}": "Algorithm delivery failed, MQTT topic only allows oortcloud/#: topic={}",
    "算法下发失败，MQTT发送异常: algorithmId={}": "Algorithm delivery failed, abnormal MQTT send: algorithmId={}",
    "算法下发失败，未找到最新训练任务: algorithmId={}": "Algorithm delivery failed, latest training task not found: algorithmId={}",
    "算法下发失败，未找到最新训练模型: algorithmId={}, trainingId={}": "Algorithm delivery failed, latest training model not found: algorithmId={}, trainingId={}",
    "算法下发失败，设备不存在": "Algorithm delivery failed, device does not exist",
    "算法下发失败，设备不存在或设备编号为空: deviceId={}": "Algorithm delivery failed, device does not exist or device number is empty: deviceId={}",
    "算法下发成功": "Algorithm delivery succeeded",
    "算法不存在": "Algorithm does not exist",
    "算法不存在：ID={}": "Algorithm does not exist: ID={}",
    "算法仓库不存在": "Algorithm repository does not exist",
    "算法仓库创建失败，名称可能已存在": "Failed to create algorithm repository, name may already exist",
    "算法仓库创建成功": "Algorithm repository created successfully",
    "算法仓库删除失败，基础预置算法库不允许删除": "Failed to delete algorithm repository, basic preset algorithm library is not allowed to be deleted",
    "算法仓库删除成功": "Algorithm repository deleted successfully",
    "算法仓库名称": "Algorithm repository name",
    "算法仓库名称已存在：{}": "Algorithm repository name already exists: {}",
    "算法仓库批量删除失败，部分仓库不允许删除": "Batch deletion of algorithm repositories failed, some repositories are not allowed to be deleted",
    "算法仓库批量删除成功": "Batch deletion of algorithm repositories succeeded",
    "算法仓库更新失败": "Failed to update algorithm repository",
    "算法仓库更新成功": "Algorithm repository updated successfully",
    "算法仓库状态批量更新失败": "Batch update of algorithm repository status failed",
    "算法仓库状态批量更新成功": "Batch update of algorithm repository status succeeded",
    "算法仓库状态更新失败": "Failed to update algorithm repository status",
    "算法仓库状态更新成功": "Algorithm repository status updated successfully",
    "算法仓库表": "Algorithm repository table",
    "算法仓库表 Excel实体类": "Algorithm repository table Excel entity class",
    "算法仓库表 Mapper 接口": "Algorithm repository table Mapper interface",
    "算法仓库表 修改": "Algorithm repository table Modify",
    "算法仓库表 分页": "Algorithm repository table Paging",
    "算法仓库表 删除": "Algorithm repository table Delete",
    "算法仓库表 包装类,返回视图层所需的字段": "Algorithm repository table wrapper class, returning fields required by the view layer",
    "算法仓库表 实体类": "Algorithm repository table entity class",
    "算法仓库表 控制器": "Algorithm repository table controller",
    "算法仓库表 数据传输对象实体类": "Algorithm repository table data transfer object entity class",
    "算法仓库表 新增": "Algorithm repository table Add",
    "算法仓库表 新增或修改": "Algorithm repository table Add or Modify",
    "算法仓库表 服务实现类": "Algorithm repository table service implementation class",
    "算法仓库表 服务类": "Algorithm repository table service class",
    "算法仓库表 自定义分页": "Algorithm repository table custom paging",
    "算法仓库表 视图实体类": "Algorithm repository table view entity class",
    "算法仓库表 详情": "Algorithm repository table details",
    "算法仓库表接口": "Algorithm repository table interface",
    "算法仓库表数据": "Algorithm repository table data",
    "算法仓库表数据表": "Algorithm repository table data table",
    "算法分类": "Algorithm category",
    "算法分类（目标检测算法、实例分割算法、图像分类算法、关键点检测算法、旋转目标检测算法等）": "Algorithm classification (object detection algorithm, instance segmentation algorithm, image classification algorithm, keypoint detection algorithm, oriented object detection algorithm, etc.)",
    "算法创建失败，同一仓库下名称可能已存在": "Failed to create algorithm, name may already exist under the same repository",
    "算法创建成功": "Algorithm created successfully",
    "算法删除失败": "Failed to delete algorithm",
    "算法删除成功": "Algorithm deleted successfully",
    "算法名称": "Algorithm name",
    "算法名称(逗号分隔)": "Algorithm names (comma-separated)",
    "算法图片URL": "Algorithm image URL",
    "算法基础模型路径为空": "Algorithm base model path is empty",
    "算法批量删除失败": "Batch deletion of algorithms failed",
    "算法批量删除成功": "Batch deletion of algorithms succeeded"
}

chunk_path = r"d:\work\ide\WorkSpace\vls-open-source\vls-server\Antigravity\dict_chunk_6.txt"
output_lines = []

with open(chunk_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

print(f"Read {len(lines)} lines from chunk")

for idx, line in enumerate(lines):
    # strip line endings
    stripped = line.rstrip("\r\n")
    if not stripped:
        output_lines.append("")
        continue
    
    parts = stripped.split(" ||| ")
    if len(parts) >= 2:
        key = parts[0]
        original = parts[1]
        
        # Look up translation
        translated = translations.get(original, "")
        if not translated:
            # Try to strip spaces or double quotes to see if we match
            translated = translations.get(original.strip(), "")
            
        if not translated:
            # Print warning for missing translations
            print(f"WARNING: Line {idx+1} translation not found for: {repr(original)}")
            translated = original # fallback to original
            
        output_lines.append(f"{key} ||| {original} ||| {translated}")
    else:
        output_lines.append(stripped)

# Write back
with open(chunk_path, "w", encoding="utf-8", newline="\n") as f:
    for line in output_lines:
        f.write(line + "\n")

print(f"Wrote {len(output_lines)} lines back")
