# -*- coding: utf-8 -*-
import os

# Translation dictionary mapping Chinese text to English text
TRANSLATION_MAP = {
    "启用动态分析": "Enable Dynamic Analysis",
    "启用或禁用算法仓库": "Enable or disable algorithm repository",
    "启用移动侦测": "Enable Motion Detection",
    "启用遮挡报警": "Enable Occlusion Alarm",
    "告警方式(site/message/sms/email/phone,逗号分隔)": "Alarm mode (site/message/sms/email/phone, comma separated)",
    "告警级别(tip/general/important/urgent)": "Alarm level (tip/general/important/urgent)",
    "告警频率(分钟/次)": "Alarm frequency (minutes/time)",
    "品牌统计内部类": "Brand statistics internal class",
    "回调地址": "Callback Address",
    "图像分类": "Image Classification",
    "图像分类事件已创建: deviceId={}, deviceName={}, algorithmId={}, results={}": "Image classification event created: deviceId={}, deviceName={}, algorithmId={}, results={}",
    "图像分类启动触发器：应用启动时触发一次图像分类任务刷新。": "Image classification startup trigger: triggers an image classification task refresh once when the application starts.",
    "图像分类截图已保存: deviceId={}, deviceName={}, time={}, path={}": "Image classification screenshot saved: deviceId={}, deviceName={}, time={}, path={}",
    "图像分类算法": "Image classification algorithm",
    "图像分类视频流断开: deviceId={}, deviceName={}, algorithmId={}": "Image classification video stream disconnected: deviceId={}, deviceName={}, algorithmId={}",
    "图像分类视频流结束: deviceId={}, deviceName={}, algorithmId={}": "Image classification video stream ended: deviceId={}, deviceName={}, algorithmId={}",
    "图像尺寸": "Image Size",
    "图片ID": "Image ID",
    "图片id": "Image ID",
    "图片上传失败:  ": "Image upload failed: ",
    "图片上传成功": "Image uploaded successfully",
    "图片信息更新成功": "Image information updated successfully",
    "图片删除成功": "Image deleted successfully",
    "图片名称": "Image Name",
    "图片名称缺少扩展名，跳过标注上传：{}": "Image name lacks extension, skip annotation upload: {}",
    "圆形": "Circle",
    "在  @{group} 新建项目 @{project}": "Created new project @{project} in  @{group}",
    "在 @{group} 新建项目 @{project}": "Created new project @{project} in @{group}",
    "在线": "Online",
    "地址": "Address",
    "场景": "Scene",
    "场景名称": "Scene Name",
    "场景治理检测编排器：按摄像头（设备）ID集合触发 detection 包下全部算法的会话刷新/停止。": "Scene governance detection orchestrator: triggers session refresh/stop of all algorithms under the detection package by camera (device) ID set.",
    "场景治理表": "Scene governance table",
    "场景治理表 Excel实体类": "Scene governance table Excel entity class",
    "场景治理表 Mapper 接口": "Scene governance table Mapper interface",
    "场景治理表 修改": "Modify scene governance table",
    "场景治理表 分页": "Scene governance table pagination",
    "场景治理表 删除": "Delete scene governance table",
    "场景治理表 包装类,返回视图层所需的字段": "Scene governance table wrapper class, returning fields required by the view layer",
    "场景治理表 实体类": "Scene governance table entity class",
    "场景治理表 控制器": "Scene governance table controller",
    "场景治理表 数据传输对象实体类": "Scene governance table data transfer object entity class",
    "场景治理表 新增": "Add scene governance table",
    "场景治理表 新增或修改": "Add or modify scene governance table",
    "场景治理表 服务实现类": "Scene governance table service implementation class",
    "场景治理表 服务类": "Scene governance table service class",
    "场景治理表 自定义分页": "Scene governance table custom pagination",
    "场景治理表 视图实体类": "Scene governance table view entity class",
    "场景治理表 详情": "Scene governance table details",
    "场景治理表接口": "Scene governance table interface",
    "场景治理表数据": "Scene governance table data",
    "场景治理表数据表": "Scene governance table database table",
    "域名地址": "Domain Address",
    "基础业务字段": "Basic business fields",
    "基础业务模式": "Basic business mode",
    "基础字段列表": "Basic field list",
    "基础字段映射": "Basic field mapping",
    "基础查询字段": "Basic query fields",
    "基础认证": "Basic Authentication",
    "基础预置": "Basic preset",
    "基础预置算法库只允许修改备注和状态": "Basic preset algorithm repository only allows modifying remarks and status",
    "堆栈": "Stack",
    "堆栈信息": "Stack info",
    "增加IP错误锁定次数": "Increase IP error lock count",
    "增加下载次数": "Increase download count",
    "增加账号错误锁定次数": "Increase account error lock count",
    "增加部署次数": "Increase deployment count",
    "增加重启次数": "Increase restart count",
    "增强配置": "Enhanced configuration",
    "增益限制": "Gain limit",
    "声强陡升:0否1是": "Sound intensity steep rise: 0 no, 1 yes",
    "声强陡升灵敏度": "Sound intensity steep rise sensitivity",
    "声强陡降:0否1是": "Sound intensity steep fall: 0 no, 1 yes",
    "声强陡降灵敏度": "Sound intensity steep fall sensitivity",
    "声音强度阈值": "Sound intensity threshold",
    "处理region字段（JSON格式）": "Process region field (JSON format)",
    "处理中": "Processing",
    "处理并上传对应的标注文件": "Process and upload the corresponding annotation file",
    "处理新增字段": "Process newly added fields",
    "处理标注数据失败：{}": "Failed to process annotation data: {}",
    "处理登录失败": "Handle login failure",
    "处理登录失败，增加失败次数": "Handle login failure, increase failure count",
    "处理登录成功": "Handle login success",
    "处理登录成功，清除失败缓存": "Handle login success, clear failure cache",
    "处理结果": "Processing result",
    "处理训练完成后的模型文件": "Process model files after training completion",
    "处理训练结果失败: {}": "Failed to process training result: {}",
    "处理训练结果失败：": "Failed to process training result: ",
    "处理设备标签": "Process device tags",
    "处理进度百分比": "Process progress percentage",
    "处理速度（FPS）": "Process speed (FPS)",
    "处理部分工具类加密不带04前缀的情况": "Handle the case where some utility classes encrypt without prefix 04",
    "备注": "Remarks",
    "备注信息": "Remarks info",
    "复制": "Copy",
    "复制截图图像失败": "Failed to copy screenshot image",
    "复制设备标签": "Copy device tags",
    "复制设备标签到其他设备": "Copy device tags to other devices",
    "复制设备标签失败": "Failed to copy device tags",
    "复制设备标签失败: sourceDeviceId={}, targetDeviceIds={}": "Failed to copy device tags: sourceDeviceId={}, targetDeviceIds={}",
    "复制设备标签成功": "Successfully copied device tags",
    "复制设备标签成功: sourceDeviceId={}, targetDeviceIds={}, tagIds={}": "Successfully copied device tags: sourceDeviceId={}, targetDeviceIds={}, tagIds={}",
    "复用已存在录制会话: strategyId={}, signature={}": "Reuse existing recording session: strategyId={}, signature={}",
    "多租户文件上传": "Multi-tenant file upload",
    "多边形": "Polygon",
    "夜间时段跳过检测: deviceId={}, deviceName={}, time={}": "Nighttime period skip detection: deviceId={}, deviceName={}, time={}",
    "失败": "Failure",
    "失败录制次数": "Failed recording count",
    "失败次数上限": "Max failure count",
    "头像": "Avatar",
    "如果不存在，新增": "If not exists, add",
    "如果不是Base64编码，则直接返回原始值，避免因格式问题导致认证失败": "If it is not Base64 encoded, return the original value directly to avoid authentication failure due to format issues",
    "如果仓库发生变化，需要更新两个仓库的算法数量": "If the repository changes, the algorithm count of both repositories needs to be updated",
    "如果存在，更新": "If exists, update",
    "如果指定了顶部菜单ID，返回角色菜单和顶部菜单的交集": "If top menu ID is specified, return the intersection of role menu and top menu",
    "如果数据集路径是相对路径，转换为绝对路径": "If the dataset path is a relative path, convert it to an absolute path",
    "如果是根级标签，不允许删除": "If it is a root-level tag, deletion is not allowed",
    "如果是部署成功，增加部署次数和更新部署时间": "If deployment is successful, increase deployment count and update deployment time",
    "如果有新标签，则批量插入": "If there are new tags, batch insert",
    "如果没有指定顶部菜单ID，返回角色对应的所有菜单": "If no top menu ID is specified, return all menus corresponding to the role",
    "如果没有配置服务器，则添加默认服务器配置": "If no server is configured, add the default server configuration",
    "如果遇到非纯数字（如 UUID 字符串 \"0ffc6e35-...\"），捕获异常并安全返回 null": "If encountering non-numeric values (such as UUID string \"0ffc6e35-...\"), catch the exception and safely return null",
    "姓名": "Name",
    "姿态估计": "Pose Estimation",
    "姿态估计事件已创建: deviceId={}, deviceName={}, algorithmId={}, joints={}": "Pose estimation event created: deviceId={}, deviceName={}, algorithmId={}, joints={}",
    "姿态估计启动触发器：应用启动时触发一次姿态估计任务刷新。": "Pose estimation startup trigger: triggers a pose estimation task refresh once when the application starts.",
    "姿态估计截图已保存: deviceId={}, deviceName={}, time={}, path={}": "Pose estimation screenshot saved: deviceId={}, deviceName={}, time={}, path={}",
    "姿态估计视频流断开: deviceId={}, deviceName={}, algorithmId={}": "Pose estimation video stream disconnected: deviceId={}, deviceName={}, algorithmId={}",
    "姿态估计视频流结束: deviceId={}, deviceName={}, algorithmId={}": "Pose estimation video stream ended: deviceId={}, deviceName={}, algorithmId={}",
    "子任务名称": "Subtask Name",
    "子孙节点": "Descendant nodes",
    "子循环任务列表": "Sub-loop task list",
    "子标签列表": "Sub-tag list",
    "字典": "Dictionary",
    "字典值": "Dictionary Value",
    "字典名称": "Dictionary Name",
    "字典备注": "Dictionary Remarks",
    "字典码": "Dictionary Code",
    "字典编号": "Dictionary Number",
    "字典表新增接口权限类型数据": "Dictionary table add interface permission type data",
    "字段策略": "Field strategy",
    "字符叠加1内容": "Character overlay 1 content",
    "字符叠加1启用:0否1是": "Character overlay 1 enabled: 0 no, 1 yes",
    "字符叠加2内容": "Character overlay 2 content",
    "字符叠加2启用:0否1是": "Character overlay 2 enabled: 0 no, 1 yes",
    "字符叠加3内容": "Character overlay 3 content",
    "字符叠加3启用:0否1是": "Character overlay 3 enabled: 0 no, 1 yes",
    "存储卷配置": "Storage volume configuration",
    "存储完成清理list": "Storage completed cleanup list",
    "存储路径": "Storage Path",
    "存入redis并设置过期时间为30分钟": "Save in redis and set expiration time to 30 minutes",
    "存在运行中的容器实例，无法删除": "Running container instance exists, cannot be deleted",
    "安全的 Long 类型处理器 (SafeLongTypeHandler)": "Safe Long type handler (SafeLongTypeHandler)",
    "完成": "Complete",
    "完成指定的标注任务": "Complete specified annotation task",
    "完成时间": "Completion Time",
    "完成标注": "Complete Annotation",
    "完成标注任务": "Complete annotation task",
    "完成标注任务：ID={}": "Completed annotation task: ID={}",
    "完整的YOLO数据集目录结构创建完成：{}": "Complete YOLO dataset directory structure creation completed: {}",
    "完结人": "Finished by",
    "完结人不能为空": "Finished by cannot be empty",
    "完结备注": "Completion Remarks",
    "完结时间": "Completion Time",
    "定义固定的设备类型": "Define fixed device types",
    "实体名": "Entity Name",
    "实体扫描，多个package用逗号或者分号分隔": "Entity scan, multiple packages separated by commas or semicolons",
    "实体类": "Entity Class",
    "实例ID列表不能为空": "Instance ID list cannot be empty",
    "实例分割": "Instance Segmentation",
    "实例分割事件已创建: deviceId={}, deviceName={}, algorithmId={}, detections={}": "Instance segmentation event created: deviceId={}, deviceName={}, algorithmId={}, detections={}",
    "实例分割启动触发器：应用启动时触发一次实例分割任务刷新。": "Instance segmentation startup trigger: triggers an instance segmentation task refresh once when the application starts.",
    "实例分割截图已保存: deviceId={}, deviceName={}, time={}, path={}": "Instance segmentation screenshot saved: deviceId={}, deviceName={}, time={}, path={}",
    "实例分割算法": "Instance segmentation algorithm",
    "实例分割视频流断开: deviceId={}, deviceName={}, algorithmId={}": "Instance segmentation video stream disconnected: deviceId={}, deviceName={}, algorithmId={}",
    "实例分割视频流结束: deviceId={}, deviceName={}, algorithmId={}": "Instance segmentation video stream ended: deviceId={}, deviceName={}, algorithmId={}",
    "实例名称": "Instance Name",
    "实例数量": "Instance Count",
    "实例状态描述": "Instance status description",
    "实例状态：running-运行中,stopped-已停止,error-错误,starting-启动中,stopping-停止中": "Instance status: running-running, stopped-stopped, error-error, starting-starting, stopping-stopping",
    "实例类型": "Instance Type",
    "审批人": "Approver",
    "审批人不能为空": "Approver cannot be empty",
    "审批意见": "Approval Opinions",
    "审批时间": "Approval Time",
    "审批状态": "Approval Status",
    "审批状态：pending/approved/rejected/completed": "Approval status: pending/approved/rejected/completed",
    "审批通过后状态流转为approved": "After approval, status transitions to approved",
    "客户端id": "Client ID",
    "客户端信息解码": "Client Information Decoding",
    "客户端密钥": "Client Secret",
    "客户端类型": "Client Type",
    "客户端认证失败!": "Client authentication failed!",
    "室内": "Indoor",
    "容器ID": "Container ID",
    "容器实例ID": "Container Instance ID",
    "容器实例不存在，ID:  ": "Container instance does not exist, ID: ",
    "容器实例已停止": "Container instance stopped",
    "容器实例已在运行中": "Container instance already running",
    "容器实例正在运行中，无法删除": "Container instance is running and cannot be deleted",
    "容器实例表": "Container instance table",
    "容器实例表 Excel实体类": "Container instance table Excel entity class",
    "容器实例表 Mapper 接口": "Container instance table Mapper interface",
    "容器实例表 修改": "Modify container instance table",
    "容器实例表 分页": "Container instance table pagination",
    "容器实例表 删除": "Delete container instance table",
    "容器实例表 包装类,返回视图层所需的字段": "Container instance table wrapper class, returning fields required by the view layer",
    "容器实例表 实体类": "Container instance table entity class",
    "容器实例表 控制器": "Container instance table controller",
    "容器实例表 数据传输对象实体类": "Container instance table data transfer object entity class",
    "容器实例表 新增": "Add container instance table",
    "容器实例表 新增或修改": "Add or modify container instance table",
    "容器实例表 服务实现类": "Container instance table service implementation class",
    "容器实例表 服务类": "Container instance table service class",
    "容器实例表 自定义分页": "Container instance table custom pagination",
    "容器实例表 视图实体类": "Container instance table view entity class",
    "容器实例表 详情": "Container instance table details",
    "容器实例表接口": "Container instance table interface",
    "容器实例表数据": "Container instance table data",
    "容器实例表数据表": "Container instance table database table",
    "宽动态": "Wide Dynamic Range",
    "密码": "Password",
    "密码(加密)": "Password (encrypted)",
    "对应模型": "Corresponding Model",
    "对比度": "Contrast",
    "对算法进行性能评估": "Evaluate performance of the algorithm",
    "对象存储端点": "Object storage endpoint",
    "对齐方式": "Alignment mode",
    "导入功能待实现": "Import function to be implemented",
    "导入成功": "Imported successfully",
    "导入时间": "Import Time",
    "导入标注数据": "Import annotation data",
    "导入标注数据：ID={}, DataPath={}": "Imported annotation data: ID={}, DataPath={}",
    "导入用户": "Import users",
    "导入用户数据": "Import user data",
    "导入设备列表": "Import device list",
    "导出指定标注的数据": "Export data of specified annotation",
    "导出数据": "Export data",
    "导出标注数据": "Export annotation data",
    "导出模板": "Export template",
    "导出用户": "Export users",
    "导出设备信息": "Export device information",
    "导出设备列表": "Export device list",
    "将key和base64返回给前端": "Return key and base64 to frontend",
    "将任意数值类型统一转为 Double，兼容 Integer/Long/Double 以及数字字符串。": "Unify any numeric type to Double, compatible with Integer/Long/Double and numeric strings.",
    "将字符串值转换为 Long": "Convert string value to Long",
    "将标注数据保存到数据集文件并更新数据库路径": "Save annotation data to dataset file and update database path",
    "将空字符串转换为null，以便SQL查询条件正确处理": "Convert empty string to null for correct handling of SQL query conditions",
    "将算法部署到指定设备": "Deploy algorithm to the specified device",
    "尝试访问指定路径": "Try to access the specified path",
    "尝试连接服务器：{}@{}": "Attempting to connect to server: {}@{}",
    "层级": "Hierarchy",
    "层级：1-标签类型，2-具体标签": "Hierarchy: 1-tag type, 2-specific tag",
    "岗位ID": "Post ID",
    "岗位id": "Post ID",
    "岗位分类名": "Post category name",
    "岗位名": "Post name",
    "岗位名称": "Post Name",
    "岗位排序": "Post sort",
    "岗位描述": "Post description",
    "岗位类型": "Post type",
    "岗位编号": "Post number",
    "岗位表": "Post table",
    "岗位表 Mapper 接口": "Post table Mapper interface",
    "岗位表 控制器": "Post table controller",
    "岗位表 服务实现类": "Post table service implementation class",
    "岗位表 服务类": "Post table service class",
    "岗位表包装类,返回视图层所需的字段": "Post table wrapper class, returning fields required by the view layer",
    "岗位表实体类": "Post table entity class",
    "岗位表接口": "Post table interface",
    "岗位表视图实体类": "Post table view entity class",
    "工作目录": "Working Directory",
    "已关闭": "Closed",
    "已发布的模型不能删除": "Published models cannot be deleted",
    "已失败": "Failed",
    "已完成": "Completed",
    "已标注数量": "Annotated count",
    "已触发重启人脸检测: deviceId={}, deviceName={}, algorithmId={}, reason={}": "Triggered restart of face detection: deviceId={}, deviceName={}, algorithmId={}, reason={}",
    "已触发重启图像分类: deviceId={}, deviceName={}, algorithmId={}, reason={}": "Triggered restart of image classification: deviceId={}, deviceName={}, algorithmId={}, reason={}",
    "已触发重启姿态估计: deviceId={}, deviceName={}, algorithmId={}, reason={}": "Triggered restart of pose estimation: deviceId={}, deviceName={}, algorithmId={}, reason={}",
    "已触发重启实例分割: deviceId={}, deviceName={}, algorithmId={}, reason={}": "Triggered restart of instance segmentation: deviceId={}, deviceName={}, algorithmId={}, reason={}",
    "已触发重启旋转框检测: deviceId={}, deviceName={}, algorithmId={}, reason={}": "Triggered restart of oriented object detection: deviceId={}, deviceName={}, algorithmId={}, reason={}",
    "已触发重启检测: deviceId={}, deviceName={}, reason={}": "Triggered restart of detection: deviceId={}, deviceName={}, reason={}",
    "已触发重启目标检测: deviceId={}, deviceName={}, algorithmId={}, reason={}": "Triggered restart of target detection: deviceId={}, deviceName={}, algorithmId={}, reason={}",
    "已通过": "Passed",
    "已驳回": "Rejected",
    "市级区划编号": "Municipal division number",
    "市级名称": "Municipal Name",
    "常规联动:0否1是": "Regular linkage: 0 no, 1 yes",
    "平均运行时间(秒)": "Average running time (seconds)",
    "应用主页": "Application Home Page",
    "应用管理": "Application Management",
    "应用管理控制器": "Application Management Controller",
    "建立 SFTP 连接": "Establish SFTP connection",
    "开始上传文件: {}": "Start uploading file: {}",
    "开始人脸检测: deviceId={}, deviceName={}, algorithmId={}, streamUrl={}": "Start face detection: deviceId={}, deviceName={}, algorithmId={}, streamUrl={}",
    "开始删除图片及相关数据：annotationId={}, imageName={}": "Start deleting image and related data: annotationId={}, imageName={}",
    "开始删除标注图片文件：ID={}, DatasetPath={}": "Start deleting annotated image file: ID={}, DatasetPath={}",
    "开始同步录像文件: strategyId={}, deviceId={}, directory={}, fileCount={}": "Start syncing video files: strategyId={}, deviceId={}, directory={}, fileCount={}",
    "开始图像分类: deviceId={}, deviceName={}, algorithmId={}, streamUrl={}": "Start image classification: deviceId={}, deviceName={}, algorithmId={}, streamUrl={}",
    "开始处理时间": "Process Start Time",
    "开始姿态估计: deviceId={}, deviceName={}, algorithmId={}, streamUrl={}": "Start pose estimation: deviceId={}, deviceName={}, algorithmId={}, streamUrl={}",
    "开始实例分割: deviceId={}, deviceName={}, algorithmId={}, streamUrl={}": "Start instance segmentation: deviceId={}, deviceName={}, algorithmId={}, streamUrl={}",
    "开始指定的标注任务": "Start specified annotation task",
    "开始指定的训练任务": "Start specified training task",
    "开始旋转框检测: deviceId={}, deviceName={}, algorithmId={}, streamUrl={}": "Start oriented object detection: deviceId={}, deviceName={}, algorithmId={}, streamUrl={}",
    "开始时间": "Start Time",
    "开始时间(当schedule_type为time_range时)": "Start time (when schedule_type is time_range)",
    "开始时间和结束时间不能为空": "Start time and end time cannot be empty",
    "开始标注任务": "Start annotation task",
    "开始标注任务：ID={}": "Start annotation task: ID={}",
    "开始检测视频流: deviceId={}, deviceName={}": "Start detecting video stream: deviceId={}, deviceName={}",
    "开始目标检测: deviceId={}, deviceName={}, algorithmId={}, streamUrl={}": "Start target detection: deviceId={}, deviceName={}, algorithmId={}, streamUrl={}",
    "开始训练任务": "Start training task",
    "开放平台授权码": "Open platform authorization code",
    "开放平台来源": "Open platform source",
    "开放平台状态吗": "Open platform status code",
    "异常信息": "Exception information",
    "异常名": "Exception name",
    "异常消息": "Exception message",
    "异步监听日志事件": "Asynchronously listen to log events",
    "异步监听错误日志事件": "Asynchronously listen to error log events",
    "强光抑制": "Strong light inhibition",
    "当前字典键值已存在!": "Current dictionary key value already exists!",
    "当前时间不在录制策略内": "Current time is not within the recording strategy",
    "当前状态不允许审批通过": "Current status does not allow approval",
    "当前状态不允许驳回": "Current status does not allow rejection",
    "当前状态不支持取消": "Current status does not support cancellation",
    "当前用户已存在!": "Current user already exists!",
    "当前轮次": "Current round",
    "当读取的值为非纯数字字符串时，返回 null，从而避免抛出 NumberFormatException 异常导致接口报错。": "When the read value is a non-numeric string, return null to avoid throwing NumberFormatException which causes interface errors.",
    "录像事件策略消息主题": "Video event strategy message topic",
    "录像入库扫描任务失败": "Video storage scan task failed",
    "录像联动:0否1是": "Video linkage: 0 no, 1 yes",
    "录像联动开启时，录像通道不能为空": "When video linkage is enabled, video channel cannot be empty",
    "录像记录URL回填失败: recordId={}, path={}": "Video record URL backfill failed: recordId={}, path={}",
    "录像记录入库失败: path={}, strategyId={}, deviceId={}": "Video record storage failed: path={}, strategyId={}, deviceId={}",
    "录像记录入库成功: recordId={}, path={}, startTime={}, endTime={}": "Video record storage succeeded: recordId={}, path={}, startTime={}, endTime={}",
    "录像通道": "Video channel",
    "录制会话参数发生变化，准备重建: strategyId={}, oldSignature={}, newSignature={}": "Recording session parameters changed, preparing to rebuild: strategyId={}, oldSignature={}, newSignature={}",
    "录制会话持久化记录": "Recording session persistent record",
    "录制参数变更，重建会话": "Recording parameter changed, rebuilding session",
    "录制开始时间": "Recording Start Time",
    "录制开始时间索引": "Recording start time index",
    "录制日期(用于按日期分组)": "Recording date (used for grouping by date)",
    "录制日期索引": "Recording date index",
    "录制格式": "Recording format",
    "录制状态": "Recording status",
    "录制状态索引": "Recording status index",
    "录制结束时间": "Recording End Time",
    "录制计划表 Excel实体类": "Recording schedule table Excel entity class",
    "录制质量": "Recording quality",
    "录制输出pattern": "Recording output pattern",
    "录制输出目录": "Recording output directory",
    "录制配置": "Recording configuration",
    "彩色日志依赖的渲染类": "Color log dependent rendering class",
    "彩色日志格式": "Color log format",
    "待处理": "Pending",
    "待审批": "Pending Approval",
    "循环周期类型(everyday/everyOtherDay/weekly/monthly)": "Cycle period type (everyday/everyOtherDay/weekly/monthly)",
    "循环周期类型不能为空": "Cycle period type cannot be empty",
    "循环治理列表": "Cycle governance list",
    "性别": "Gender",
    "总录制次数": "Total recording count",
    "总数量": "Total Quantity",
    "总轮次": "Total rounds",
    "恢复默认值": "Restore default values",
    "懒加载列表": "Lazy load list",
    "懒加载菜单列表": "Lazy load menu list",
    "成功删除图片及相关数据：imageId={}": "Successfully deleted image and related data: imageId={}",
    "成功率": "Success rate",
    "成功读取文件内容：{}": "Successfully read file content: {}",
    "截图URL": "Screenshot URL",
    "截图信息": "Screenshot information",
    "截图数量": "Screenshot quantity",
    "所在公司": "Company location",
    "所属算法仓库ID": "Belonging algorithm repository ID",
    "所有菜单": "All menus",
    "手机": "Mobile phone",
    "打印日志级别": "Print log level",
    "执行RTSP录制刷新：timeStrategyCount={}, recordEventStrategyCount={}, activeSessionCount={}, segmentSeconds={}": "Execute RTSP recording refresh: timeStrategyCount={}, recordEventStrategyCount={}, activeSessionCount={}, segmentSeconds={}",
    "执行SSH命令": "Execute SSH command",
    "执行SSH命令，如果认证失败则使用默认配置的SSH账号重试一次。": "Execute SSH command, if authentication fails, retry once using the SSH account in default configuration.",
    "执行人": "Executor",
    "执行人ID列表": "Executor ID list",
    "执行命令": "Execute command",
    "执行时间": "Execution Time",
    "执行模型部署逻辑...": "Executing model deployment logic...",
    "执行模式：serial-串行,parallel-并行": "Execution mode: serial-serial, parallel-parallel",
    "执行类型": "Execution type",
    "执行软删除": "Execute soft delete",
    "扩展": "Extension",
    "批大小": "Batch size",
    "批量保存后更新统计信息失败: annotationId={}, error={}": "Failed to update statistical info after batch save: annotationId={}, error={}",
    "批量保存图片信息到annotation_image表": "Batch save image information to annotation_image table",
    "批量保存图片信息失败": "Failed to batch save image information",
    "批量保存图片信息失败:  ": "Failed to batch save image information: ",
    "批量保存图片信息成功": "Successfully batch saved image information",
    "批量保存图片信息，数量: {}": "Batch save image information, quantity: {}"
}

def translate_file(input_path):
    """
    Reads the chunk file, translates each line using the mapping, 
    and writes it back ensuring formatting, keys, and line count match.
    """
    if not os.path.exists(input_path):
        print(f"Error: {input_path} does not exist.")
        return
        
    with open(input_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        
    print(f"Total lines read: {len(lines)}")
    
    output_lines = []
    translated_count = 0
    not_translated_count = 0
    
    for i, line in enumerate(lines, 1):
        stripped_line = line.strip()
        if not stripped_line:
            output_lines.append(line)
            continue
            
        parts = stripped_line.split(" ||| ")
        if len(parts) >= 2:
            base64_key = parts[0]
            original_text = parts[1]
            
            # Find translation
            translation = TRANSLATION_MAP.get(original_text)
            if translation:
                new_line = f"{base64_key} ||| {original_text} ||| {translation}\n"
                translated_count += 1
            else:
                # Keep original if translation not found or empty
                new_line = f"{base64_key} ||| {original_text} ||| \n"
                not_translated_count += 1
                print(f"Warning: No translation found for '{original_text}' at line {i}")
            output_lines.append(new_line)
        else:
            output_lines.append(line)
            
    # Write back to file
    with open(input_path, 'w', encoding='utf-8', newline='\n') as f:
        f.writelines(output_lines)
        
    print(f"Total lines written: {len(output_lines)}")
    print(f"Translated: {translated_count}, Not translated: {not_translated_count}")

if __name__ == "__main__":
    chunk_path = r"d:\work\ide\WorkSpace\vls-open-source\vls-server\Antigravity\dict_chunk_3.txt"
    translate_file(chunk_path)
