[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$translations = [System.Collections.Generic.Dictionary[string, string]]::new([System.StringComparer]::Ordinal)
$dictData = @(
    @('@return 运行中的容器实例列表', '@return List of running container instances'),
    @('@return 远程服务器配置', '@return Remote server configuration'),
    @('@return 远程服务器配置集合', '@return Collection of remote server configurations'),
    @('@return 连接结果', '@return Connection result'),
    @('@return 部署状态统计信息', '@return Deployment status statistics'),
    @('@return 配置参数', '@return Configuration parameters'),
    @('@return 验证结果', '@return Verification results'),
    @('AI算法不能为空', 'AI algorithm cannot be empty'),
    @('Ant Design Pro 是一个企业级开箱即用的中后台前端/设计解决方案。符合阿里追求的''敏捷的前端+强大的中台''的思想。', 'Ant Design Pro is an enterprise-class out-of-the-box mid-and-back-end front-end/design solution. It conforms to Alibaba''s philosophy of ''agile front-end + powerful mid-end''.'),
    @('ApiScopeVO对象', 'ApiScopeVO object'),
    @('ApiScope对象', 'ApiScope object'),
    @('AudioAnomalyDetectionSetting对象', 'AudioAnomalyDetectionSetting object'),
    @('AudioDefenseTimeSetting对象', 'AudioDefenseTimeSetting object'),
    @('AudioLinkageModeSetting对象', 'AudioLinkageModeSetting object'),
    @('Base64内容长度: {}', 'Base64 content length: {}'),
    @('Blade单元测试', 'Blade unit test'),
    @('Blade配置', 'Blade configuration'),
    @('CPU使用率', 'CPU usage'),
    @('CPU型号', 'CPU model'),
    @('CPU限制', 'CPU limit'),
    @('CameraApplyRecord对象', 'CameraApplyRecord object'),
    @('CameraDisplaySetting对象', 'CameraDisplaySetting object'),
    @('CameraOsdSetting对象', 'CameraOsdSetting object'),
    @('Client对象', 'Client object'),
    @('Code对象', 'Code object'),
    @('Conda环境名称', 'Conda environment name'),
    @('Conda诊断失败: ', 'Conda diagnosis failed: '),
    @('Conda诊断失败: {}', 'Conda diagnosis failed: {}'),
    @('Conda诊断异常: ', 'Conda diagnosis anomaly: '),
    @('Conda诊断异常: {}', 'Conda diagnosis anomaly: {}'),
    @('Conda诊断成功: {}', 'Conda diagnosis succeeded: {}'),
    @('Conda诊断结果:\n', 'Conda diagnosis result:\n'),
    @('Copyright (c) 2018-2099, Chill Zhuang 庄骞 (bladejava@qq.com).', 'Copyright (c) 2018-2099, Chill Zhuang 庄骞 (bladejava@qq.com).'),
    @('DataScopeVO对象', 'DataScopeVO object'),
    @('DataScope对象', 'DataScope object'),
    @('Datasource对象', 'Datasource object'),
    @('DeptVO对象', 'DeptVO object'),
    @('Dept对象', 'Dept object'),
    @('DictVO对象', 'DictVO object'),
    @('Dict对象', 'Dict object'),
    @('FFmpeg配置', 'FFmpeg configuration'),
    @('GPU使用率', 'GPU usage'),
    @('GPU描述', 'GPU description'),
    @('GPU限制', 'GPU limit'),
    @('HLS输出配置', 'HLS output configuration'),
    @('IP地址 (支持IPv4和IPv6)', 'IP address (supports IPv4 and IPv6)'),
    @('IP锁定key', 'IP lock key'),
    @('Log包装类,返回视图层所需的字段', 'Log wrapper class, returning fields required by the view layer'),
    @('MQTT客户端ID前缀', 'MQTT client ID prefix'),
    @('MQTT密码', 'MQTT password'),
    @('MQTT心跳保持时长（秒）', 'MQTT keep-alive duration (seconds)'),
    @('MQTT服务地址', 'MQTT service address'),
    @('MQTT服务端口', 'MQTT service port'),
    @('MQTT消息发送失败，topic仅允许oortcloud/#: topic={}', 'Failed to send MQTT message, topic only allows oortcloud/#: topic={}'),
    @('MQTT消息发送异常: topic={}', 'MQTT message sending exception: topic={}'),
    @('MQTT消息发送服务', 'MQTT message sending service'),
    @('MQTT消息质量等级', 'MQTT message Quality of Service (QoS)'),
    @('MQTT用户名', 'MQTT username'),
    @('MQTT连接超时（秒）', 'MQTT connection timeout (seconds)'),
    @('MQTT配置', 'MQTT configuration'),
    @('Mapper 接口', 'Mapper interface'),
    @('MenuVO对象', 'MenuVO object'),
    @('Menu对象', 'Menu object'),
    @('MobileSceneGovernanceSubTask对象', 'MobileSceneGovernanceSubTask object'),
    @('MobileSceneGovernance对象', 'MobileSceneGovernance object'),
    @('MyBatis 是一款优秀的持久层框架，它支持定制化 SQL、存储过程以及高级映射。MyBatis 避免了几乎所有的 JDBC 代码和手动设置参数以及获取结果集。MyBatis 可以使用简单的 XML 或注解来配置和映射原生信息，将接口和 Java 的 POJOs(Plain Old Java Objects,普通的 Java对象)映射成数据库中的记录。', 'MyBatis is an outstanding persistence framework that supports customized SQL, stored procedures, and advanced mapping. MyBatis avoids almost all JDBC code, manual parameter setting, and retrieval of results. MyBatis can be configured and mapped from native information using simple XML or annotations, mapping interfaces and Java POJOs (Plain Old Java Objects) into database records.'),
    @('Notice包装类,返回视图层所需的字段', 'Notice wrapper class, returning fields required by the view layer'),
    @('OSD字体', 'OSD font'),
    @('OSD属性', 'OSD properties'),
    @('OSD颜色', 'OSD color'),
    @('PTZ停止成功', 'PTZ stop succeeded'),
    @('PTZ控制', 'PTZ control'),
    @('PTZ控制 - 停止', 'PTZ control - Stop'),
    @('PTZ控制 - 移动', 'PTZ control - Move'),
    @('PTZ控制 - 缩放', 'PTZ control - Zoom'),
    @('PTZ控制: 设备={}, 命令={}, 参数={}', 'PTZ control: device={}, command={}, parameters={}'),
    @('PTZ控制失败: ', 'PTZ control failed: '),
    @('PTZ控制失败: {}', 'PTZ control failed: {}'),
    @('PTZ控制成功', 'PTZ control succeeded'),
    @('PTZ移动成功: ', 'PTZ move succeeded: '),
    @('PTZ缩放成功: ', 'PTZ zoom succeeded: '),
    @('ParamVO对象', 'ParamVO object'),
    @('Param对象', 'Param object'),
    @('PostVO对象', 'PostVO object'),
    @('Post对象', 'Post object'),
    @('RTSP地址', 'RTSP address'),
    @('RTSP录制功能未启用', 'RTSP recording function not enabled'),
    @('RTSP录制进程管理器', 'RTSP recording process manager'),
    @('RTSP录制配置', 'RTSP recording configuration'),
    @('React 起源于 Facebook 的内部项目，因为该公司对市场上所有 JavaScript MVC 框架，都不满意，就决定自己写一套，用来架设Instagram 的网站。做出来以后，发现这套东西很好用，就在2013年5月开源了。', 'React originated as an internal project at Facebook. Because the company was unsatisfied with all existing JavaScript MVC frameworks on the market, they decided to write their own to build the Instagram website. Once built, they found it very useful and open-sourced it in May 2013.'),
    @('RecordEventStrategy对象', 'RecordEventStrategy object'),
    @('RecordingSession对象', 'RecordingSession object'),
    @('RegionVO对象', 'RegionVO object'),
    @('Region对象', 'Region object'),
    @('ResourceSpec对象', 'ResourceSpec object'),
    @('ResourceType对象', 'ResourceType object'),
    @('RoleMenuVO对象', 'RoleMenuVO object'),
    @('RoleMenu对象', 'RoleMenu object'),
    @('RoleScope对象', 'RoleScope object'),
    @('RoleVO对象', 'RoleVO object'),
    @('Role对象', 'Role object'),
    @('SSH命令执行: {}', 'SSH command execution: {}'),
    @('SSH命令执行失败: {}', 'SSH command execution failed: {}'),
    @('SSH命令执行完成，输出长度: {}, 错误长度: {}', 'SSH command execution completed, output length: {}, error length: {}'),
    @('SSH命令执行输出: {}', 'SSH command execution output: {}'),
    @('SSH命令执行错误信息: {}', 'SSH command execution error info: {}'),
    @('SSH执行结果类', 'SSH execution result class'),
    @('SSH端口', 'SSH port'),
    @('SSH连接成功: {}@{}:{}', 'SSH connection succeeded: {}@{}:{}'),
    @('SSH连接成功：{}@{}', 'SSH connection succeeded: {}@{}'),
    @('SSH连接服务类', 'SSH connection service class'),
    @('SSH连接测试失败: {}', 'SSH connection test failed: {}'),
    @('SSH连接测试成功: {}@{}:{}', 'SSH connection test succeeded: {}@{}:{}'),
    @('SSH连接配置', 'SSH connection configuration'),
    @('Secure工具类', 'Secure utility class'),
    @('SpringBlade 接口文档系统', 'SpringBlade API Document System'),
    @('SpringCloud是基于SpringBoot的一整套实现微服务的框架。他提供了微服务开发所需的配置管理、服务发现、断路器、智能路由、微代理、控制总线、全局锁、决策竞选、分布式会话和集群状态管理等组件。', 'Spring Cloud is a microservices framework built on top of Spring Boot. It provides components needed for microservices development, such as configuration management, service discovery, circuit breakers, intelligent routing, micro-proxy, control bus, global lock, leadership election, distributed sessions, and cluster state management.'),
    @('Swagger配置类', 'Swagger configuration class'),
    @('TODO: 实现文件解析和设备导入功能', 'TODO: Implement file parsing and device import functions'),
    @('TODO: 根据设备类型和命令执行PTZ控制', 'TODO: Execute PTZ control based on device type and command'),
    @('TODO: 根据设备类型和连接参数测试连接', 'TODO: Test connection based on device type and connection parameters'),
    @('TODO: 集成Docker API', 'TODO: Integrate Docker API'),
    @('Tenant对象', 'Tenant object'),
    @('TokenGranter缓存池', 'TokenGranter cache pool'),
    @('UserVO对象', 'UserVO object'),
    @('VLStream Cloud 视频流管理系统接口文档系统', 'VLStream Cloud video stream management system API document system'),
    @('VLStream Cloud 视频流管理系统接口文档系统(服务名apaas-vls-server)', 'VLStream Cloud video stream management system API document system (service name: apaas-vls-server)'),
    @('VlsAlgorithmAnnotationEntity对象', 'VlsAlgorithmAnnotationEntity object'),
    @('VlsAlgorithmEntity对象', 'VlsAlgorithmEntity object'),
    @('VlsAlgorithmModelEntity对象', 'VlsAlgorithmModelEntity object'),
    @('VlsAlgorithmOrchestrationEntity对象', 'VlsAlgorithmOrchestrationEntity object'),
    @('VlsAlgorithmRepositoryEntity对象', 'VlsAlgorithmRepositoryEntity object'),
    @('VlsAlgorithmTrainingEntity对象', 'VlsAlgorithmTrainingEntity object'),
    @('VlsAnalysisRequestEntity对象', 'VlsAnalysisRequestEntity object'),
    @('VlsAnnotationImageEntity对象', 'VlsAnnotationImageEntity object'),
    @('VlsAnnotationInstanceEntity对象', 'VlsAnnotationInstanceEntity object'),
    @('VlsAnnotationLabelEntity对象', 'VlsAnnotationLabelEntity object'),
    @('VlsContainerInstanceEntity对象', 'VlsContainerInstanceEntity object'),
    @('VlsDeviceInfoEntity对象', 'VlsDeviceInfoEntity object'),
    @('VlsDeviceTagRelationEntity对象', 'VlsDeviceTagRelationEntity object'),
    @('VlsEventManagementEntity对象', 'VlsEventManagementEntity object'),
    @('VlsRemoteServersEntity对象', 'VlsRemoteServersEntity object'),
    @('VlsSceneGovernanceEntity对象', 'VlsSceneGovernanceEntity object'),
    @('VlsTagManagementEntity对象', 'VlsTagManagementEntity object'),
    @('VlsTimeStrategyEntity对象', 'VlsTimeStrategyEntity object'),
    @('VlsVideoRecordEntity对象', 'VlsVideoRecordEntity object'),
    @('XXXX年XX月XX日', 'XXXX-XX-XX'),
    @('YOLOv8训练服务器', 'YOLOv8 training server'),
    (@('] 个', '] items')),
    @('annotationId不合法', 'annotationId is invalid'),
    @('annotationType不合法', 'annotationType is invalid'),
    @('annotationType不能为空', 'annotationType cannot be empty'),
    @('apiScopeIds集合', 'apiScopeIds collection'),
    @('blade配置', 'blade configuration'),
    @('cron表达式', 'cron expression'),
    @('dataScopeIds集合', 'dataScopeIds collection'),
    @('echo ''=== Python环境 ==='' && ', 'echo ''=== Python Environment ==='' && '),
    @('echo ''=== 完成 ===''', 'echo ''=== Completed ==='''),
    @('echo ''=== 查找conda ==='' && ', 'echo ''=== Find conda ==='' && '),
    @('echo ''=== 查找conda.sh ==='' && ', 'echo ''=== Find conda.sh ==='' && '),
    @('echo ''=== 查找yolo ==='' && ', 'echo ''=== Find yolo ==='' && '),
    @('echo ''=== 环境诊断 ==='' && ', 'echo ''=== Environment Diagnosis ==='' && '),
    @('imageId不能为空', 'imageId cannot be empty'),
    @('instances不能为空', 'instances cannot be empty'),
    @('instances格式不合法', 'instances format is invalid'),
    @('int8 rknn模型输出路径', 'int8 rknn model output path'),
    @('knife4j配置', 'knife4j configuration'),
    @('labelId不能为空', 'labelId cannot be empty'),
    @('labelId或imageId不能为空', 'labelId or imageId cannot be empty'),
    @('log.info("SSH命令执行输出: {}", output);', 'log.info("SSH command execution output: {}", output);'),
    @('log.warn("SSH命令执行错误信息: {}", error);', 'log.warn("SSH command execution error info: {}", error);'),
    @('mAP值', 'mAP value'),
    @('menuIds集合', 'menuIds collection'),
    @('name:缓存名称。\r\n        maxElementsInMemory：缓存最大个数。\r\n        eternal:对象是否永久有效，一但设置了，timeout将不起作用。\r\n        timeToIdleSeconds：设置对象在失效前的允许闲置时间（单位：秒）。仅当eternal=false对象不是永久有效时使用，可选属性，默认值是0，也就是可闲置时间无穷大。\r\n        timeToLiveSeconds：设置对象在失效前允许存活时间（单位：秒）。最大时间介于创建时间和失效时间之间。仅当eternal=false对象不是永久有效时使用，默认是0.，也就是对象存活时间无穷大。\r\n        overflowToDisk：当内存中对象数量达到maxElementsInMemory时，Ehcache将会对象写到磁盘中。\r\n        diskSpoolBufferSizeMB：这个参数设置DiskStore（磁盘缓存）的缓存区大小。默认是30MB。每个Cache都应该有自己的一个缓冲区。\r\n        maxElementsOnDisk：硬盘最大缓存个数。\r\n        diskPersistent：是否缓存虚拟机重启期数据 Whether the disk store persists between restarts of the Virtual Machine. The default value is false.\r\n        diskExpiryThreadIntervalSeconds：磁盘失效线程运行时间间隔，默认是120秒。\r\n        memoryStoreEvictionPolicy：当达到maxElementsInMemory限制时，Ehcache将会根据指定的策略去清理内存。默认策略是LRU（最近最少使用）。你可以设置为FIFO（先进先出）或是LFU（较少使用）。\r\n        clearOnFlush：内存数量最大时是否清除。', 'name: Cache name.\r\n        maxElementsInMemory: Maximum number of elements in memory.\r\n        eternal: Whether the object is permanently valid. Once set, timeout will have no effect.\r\n        timeToIdleSeconds: Set the allowed idle time for an object before it expires (unit: seconds). Used only when eternal=false (the object is not permanently valid), optional attribute, default value is 0, which means infinite idle time.\r\n        timeToLiveSeconds: Set the allowed lifespan for an object before it expires (unit: seconds). The maximum time is between the creation time and expiration time. Used only when eternal=false (the object is not permanently valid), default value is 0, which means infinite lifespan.\r\n        overflowToDisk: When the number of objects in memory reaches maxElementsInMemory, Ehcache will write the objects to disk.\r\n        diskSpoolBufferSizeMB: This parameter sets the buffer size of the DiskStore (disk cache). The default is 30MB. Each Cache should have its own buffer.\r\n        maxElementsOnDisk: Maximum number of cache elements on the hard disk.\r\n        diskPersistent: Whether to cache data across virtual machine restarts. Whether the disk store persists between restarts of the Virtual Machine. The default value is false.\r\n        diskExpiryThreadIntervalSeconds: Interval for running the disk expiration thread, default is 120 seconds.\r\n        memoryStoreEvictionPolicy: When the maxElementsInMemory limit is reached, Ehcache will clear memory based on the specified policy. The default policy is LRU (Least Recently Used). You can set it to FIFO (First In First Out) or LFU (Less Frequently Used).\r\n        clearOnFlush: Whether to clear when memory capacity reaches maximum.'),
    @('notice数量：[', 'number of notices: ['),
    @('onnx模型文件路径', 'onnx model file path'),
    @('onnx模型输出路径', 'onnx model output path'),
    @('oracle 版本', 'oracle version'),
    @('oss配置', 'oss configuration'),
    @('pt模型文件路径', 'pt model file path'),
    @('rknn模型文件路径', 'rknn model file path'),
    @('rknn模型输出路径', 'rknn model output path'),
    @('roleIds集合', 'roleIds collection'),
    @('roleId集合', 'roleId collection'),
    @('saber 系统名', 'saber system name'),
    @('saber配置\n" +', 'saber configuration\n" +'),
    @('sentinel dev 地址', 'sentinel dev address'),
    @('sentinel prod 地址', 'sentinel prod address'),
    @('sentinel test 地址', 'sentinel test address'),
    @('signKey生成器', 'signKey generator'),
    @('springdoc-openapi配置', 'springdoc-openapi configuration'),
    @('spring配置', 'spring configuration'),
    @('ssh配置', 'ssh configuration'),
    @('swagger配置信息', 'swagger configuration info'),
    @('sword 系统名', 'sword system name'),
    @('synset文件', 'synset file'),
    @('topMenuIds集合', 'topMenuIds collection'),
    @('userId集合', 'userId collection'),
    @('vCPU核数', 'vCPU cores'),
    @('vls模块', 'vls module'),
    @('yolo工作路径', 'yolo working path'),
    @('{} Base64长度: deviceId={}, deviceName={}, length={}', '{} Base64 length: deviceId={}, deviceName={}, length={}'),
    @('七月月迭代', 'July monthly iteration'),
    @('上传中心:0否1是', 'Upload center: 0 No, 1 Yes'),
    @('上传图片', 'Upload image'),
    @('上传图片后更新标注总数失败: annotationId={}, error={}', 'Failed to update annotation count after uploading image: annotationId={}, error={}'),
    @('上传数据集 YAML 文件', 'Upload dataset YAML file'),
    @('上传文件', 'Upload file'),
    @('上传文件到文件存储服务', 'Upload file to file storage service'),
    @('上传标注图片', 'Upload annotated image'),
    @('上传标注文件到训练/验证目录', 'Upload annotation files to training/validation directory'),
    @('上传视频缩略图失败: videoPath={}, thumbnailPath={}', 'Failed to upload video thumbnail: videoPath={}, thumbnailPath={}'),
    @('上报事件', 'Report event'),
    @('上报位置', 'Report location'),
    @('上报图片', 'Report image'),
    @('上报时间', 'Report time'),
    @('上报设备', 'Report device'),
    @('上级字典', 'Parent dictionary'),
    @('上级菜单', 'Parent menu'),
    @('上级角色', 'Parent role'),
    @('上级部门', 'Parent department'),
    @('下拉数据源', 'Dropdown data source'),
    @('下次录制时间', 'Next recording time'),
    @('下载文件', 'Download file'),
    @('下载文件失败：', 'Failed to download file: '),
    @('下载文件：host={}, path={}, filename={}', 'Download file: host={}, path={}, filename={}'),
    @('下载模型', 'Download model'),
    @('下载模型失败', 'Failed to download model'),
    @('下载模型失败：', 'Failed to download model: '),
    @('下载模型成功：{}', 'Model downloaded successfully: {}'),
    @('下载模型文件', 'Download model file'),
    @('下载模型文件: {}', 'Download model file: {}'),
    @('下载模型文件失败: {}', 'Failed to download model file: {}'),
    @('下载次数', 'Download count'),
    @('下载算法模型：{}', 'Download algorithm model: {}'),
    @('不允许删除基础预置算法库：ID={}', 'Deleting basic preset algorithm library is not allowed: ID={}'),
    @('不抛出异常，继续执行后续逻辑', 'Do not throw exception, continue with subsequent logic'),
    @('不支持的循环周期类型', 'Unsupported loop cycle type'),
    @('不能删除根级标签分类', 'Cannot delete root label classification'),
    @('不透明、不闪烁', 'Opaque, non-flashing'),
    @('不阻止删除操作，只记录错误', 'Do not block delete operation, only log error'),
    @('不阻止应用启动，只记录警告', 'Do not block application startup, only log warning'),
    @('业务日志', 'Business log'),
    @('业务配置', 'Business configuration'),
    @('中', 'Medium'),
    @('临时图片删除失败：{}', 'Failed to delete temporary image: {}'),
    @('临时标注文件删除失败：{}', 'Failed to delete temporary annotation file: {}'),
    @('临时配置文件删除失败：{}', 'Failed to delete temporary configuration file: {}'),
    @('为每个标签类型构建子标签', 'Build child labels for each label type'),
    @('为每个目标设备设置标签', 'Set labels for each target device'),
    @('主任务ID', 'Main task ID'),
    @('主键', 'Primary key'),
    @('主键ID', 'Primary key ID'),
    @('主键id', 'Primary key ID'),
    @('主键名', 'Primary key name'),
    @('主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";', 'Primary key type  0:"Database ID auto-increment", 1:"No operation", 2:"User input ID", 3:"Numeric snowflake", 4:"Global unique ID UUID", 5:"String snowflake";'),
    @('主键集合', 'Primary key collection'),
    @('事件ID', 'Event ID'),
    @('事件描述', 'Event description'),
    @('事件数据', 'Event data'),
    @('事件状态', 'Event status'),
    @('事件状态枚举', 'Event status enum'),
    @('事件状态：pending-待处理,processing-处理中,completed-已完成,closed-已关闭', 'Event status: pending-Pending, processing-Processing, completed-Completed, closed-Closed'),
    @('事件策略或时间策略已删除/禁用', 'Event strategy or time strategy has been deleted/disabled'),
    @('事件策略明确禁用录制(triggerAction不含record): strategyDeviceId={}, triggerAction={}', 'Event strategy explicitly disables recording (triggerAction does not contain record): strategyDeviceId={}, triggerAction={}'),
    @('事件策略未配置triggerAction，按默认启用录制: strategyDeviceId={}', 'Event strategy does not configure triggerAction, enabling recording by default: strategyDeviceId={}'),
    @('事件管理表', 'Event management table'),
    @('事件管理表 Excel实体类', 'Event management table Excel entity class'),
    @('事件管理表 Mapper 接口', 'Event management table Mapper interface'),
    @('事件管理表 修改', 'Event management table Modification'),
    @('事件管理表 分页', 'Event management table Pagination'),
    @('事件管理表 删除', 'Event management table Deletion'),
    @('事件管理表 包装类,返回视图层所需的字段', 'Event management table wrapper class, returning fields required by the view layer'),
    @('事件管理表 实体类', 'Event management table Entity class'),
    @('事件管理表 控制器', 'Event management table Controller'),
    @('事件管理表 数据传输对象实体类', 'Event management table Data Transfer Object (DTO) entity class'),
    @('事件管理表 新增', 'Event management table Add'),
    @('事件管理表 新增或修改', 'Event management table Add or Modify'),
    @('事件管理表 服务实现类', 'Event management table Service implementation class'),
    @('事件管理表 服务类', 'Event management table Service class'),
    @('事件管理表 自定义分页', 'Event management table Custom pagination'),
    @('事件管理表 视图实体类', 'Event management table View entity class'),
    @('事件管理表 详情', 'Event management table Details'),
    @('事件管理表接口', 'Event management table interface'),
    @('事件管理表数据', 'Event management table data'),
    @('事件管理表数据表', 'Event management table data table'),
    @('事件类型', 'Event type'),
    @('事件级别', 'Event level'),
    @('事件级别枚举', 'Event level enum'),
    @('事件级别：low-低,medium-中,high-高,urgent-紧急', 'Event level: low-Low, medium-Medium, high-High, urgent-Urgent'),
    @('云台', 'PTZ'),
    @('亮度', 'Brightness'),
    @('亮度过低，跳过检测: deviceId={}, deviceName={}, brightness={}', 'Brightness too low, skipping detection: deviceId={}, deviceName={}, brightness={}'),
    @('亮度限制', 'Brightness limit'),
    @('人体检测', 'Human body detection'),
    @('人体检测启动触发器：应用启动时触发一次人体检测任务刷新。', 'Human body detection startup trigger: triggers a human body detection task refresh once when the application starts.'),
    @('人脸检测', 'Face detection'),
    @('人脸检测事件已创建: deviceId={}, deviceName={}, algorithmId={}, faces={}', 'Face detection event created: deviceId={}, deviceName={}, algorithmId={}, faces={}'),
    @('人脸检测启动触发器：应用启动时触发一次人脸检测任务刷新。', 'Face detection startup trigger: triggers a face detection task refresh once when the application starts.'),
    @('人脸检测截图已保存: deviceId={}, deviceName={}, time={}, path={}', 'Face detection snapshot saved: deviceId={}, deviceName={}, time={}, path={}'),
    @('人脸检测视频流断开: deviceId={}, deviceName={}, algorithmId={}', 'Face detection video stream disconnected: deviceId={}, deviceName={}, algorithmId={}'),
    @('人脸检测视频流结束: deviceId={}, deviceName={}, algorithmId={}', 'Face detection video stream ended: deviceId={}, deviceName={}, algorithmId={}'),
    @('人脸识别算法', 'Face recognition algorithm'),
    @('仅approved状态可完结为completed', 'Only approved status can be concluded as completed'),
    @('仅审批通过记录允许完结', 'Only approved records are allowed to be concluded'),
    @('从标注实例中提取图片名，imageId 为空时用于兜底匹配', 'Extract image name from annotation instance, used as fallback matching when imageId is empty'),
    @('从标注数据中提取图片名称列表', 'Extract image name list from annotation data'),
    @('从标注数据中提取图片数量', 'Extract image count from annotation data'),
    @('从标注数据中提取标注列表', 'Extract annotation list from annotation data'),
    @('从标注数据中提取类别信息', 'Extract category information from annotation data'),
    @('从请求数据中提取设备信息', 'Extract device information from request data'),
    @('从远程服务器下载指定文件', 'Download specified file from remote server'),
    @('从远程服务器下载文件', 'Download file from remote server'),
    @('从远程服务器下载训练好的模型文件', 'Download trained model file from remote server'),
    @('仓库ID', 'Repository ID'),
    @('仓库类型', 'Repository type'),
    @('仓库类型枚举', 'Repository type enum'),
    @('仓库类型：basic-基础预置, extended-扩展', 'Repository type: basic-Basic Preset, extended-Extended'),
    @('付小小', 'Fu Xiaoxiao'),
    @('代码所在服务名', 'Service name where code resides'),
    @('代码生成', 'Code generation'),
    @('代码生成器', 'Code generator'),
    @('代码生成成功', 'Code generation succeeded'),
    @('代码生成的包名', 'Package name of generated code'),
    @('代码生成的模块名', 'Module name of generated code'),
    @('令牌', 'Token'),
    @('令牌类型', 'Token type'),
    @('令牌过期秒数', 'Token expiration seconds'),
    @('以下为关联对象，不对应数据库字段', 'The following are associated objects and do not correspond to database fields'),
    @('以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理', 'The following configuration will affect buffers, which will be used for IO operations of server connections, similar to Netty''s pooled memory management'),
    @('任务名称', 'Task name'),
    @('任务状态(pending/done/cancel)', 'Task status (pending/done/cancel)'),
    @('任务需要在 2018-01-12 20:00 前启动', 'Task needs to start before 2018-01-12 20:00'),
    @('优先从 request 中获取', 'Obtain from request preferentially'),
    @('会话开始时间', 'Session start time'),
    @('会话状态 running/stopped', 'Session status running/stopped'),
    @('会话签名', 'Session signature'),
    @('会话结束时间', 'Session end time'),
    @('传入User', 'Pass in User'),
    @('传入account和realName', 'Pass in account and realName'),
    @('传入cameraDisplaySetting', 'Pass in cameraDisplaySetting'),
    @('传入cameraOsdSetting', 'Pass in cameraOsdSetting'),
    @('传入client', 'Pass in client'),
    @('传入code', 'Pass in code'),
    @('传入dataScope', 'Pass in dataScope'),
    @('传入datasource', 'Pass in datasource'),
    @('传入dept', 'Pass in dept'),
    @('传入deviceId', 'Pass in deviceId'),
    @('传入deviceId与时间段', 'Pass in deviceId and time period'),
    @('传入dict', 'Pass in dict'),
    @('传入domain', 'Pass in domain'),
    @('传入excel', 'Pass in excel'),
    @('传入id', 'Pass in id'),
    @('传入ids', 'Pass in ids'),
    @('传入menu', 'Pass in menu'),
    @('传入notice', 'Pass in notice'),
    @('传入param', 'Pass in param'),
    @('传入post', 'Pass in post'),
    @('传入region', 'Pass in region'),
    @('传入resourceSpec', 'Pass in resourceSpec'),
    @('传入resourceType', 'Pass in resourceType'),
    @('传入role', 'Pass in role'),
    @('传入roleId集合以及menuId集合', 'Pass in roleId collection and menuId collection'),
    @('传入tenant', 'Pass in tenant'),
    @('传入topMenu', 'Pass in topMenu'),
    @('传入topMenuId集合以及menuId集合', 'Pass in topMenuId collection and menuId collection'),
    @('传入user', 'Pass in user'),
    @('传入userId集合', 'Pass in userId collection'),
    @('传入vlsAlgorithm', 'Pass in vlsAlgorithm'),
    @('传入vlsAlgorithmAnnotation', 'Pass in vlsAlgorithmAnnotation'),
    @('传入vlsAlgorithmModel', 'Pass in vlsAlgorithmModel'),
    @('传入vlsAlgorithmOrchestration', 'Pass in vlsAlgorithmOrchestration'),
    @('传入vlsAlgorithmRepository', 'Pass in vlsAlgorithmRepository'),
    @('传入vlsAlgorithmTraining', 'Pass in vlsAlgorithmTraining'),
    @('传入vlsAnalysisRequest', 'Pass in vlsAnalysisRequest'),
    @('传入vlsAnnotationImage', 'Pass in vlsAnnotationImage'),
    @('传入vlsAnnotationInstance', 'Pass in vlsAnnotationInstance'),
    @('传入vlsAnnotationLabel', 'Pass in vlsAnnotationLabel'),
    @('传入vlsContainerInstance', 'Pass in vlsContainerInstance'),
    @('传入vlsDeviceInfo', 'Pass in vlsDeviceInfo'),
    @('传入vlsDeviceTagRelation', 'Pass in vlsDeviceTagRelation'),
    @('传入vlsEventManagement', 'Pass in vlsEventManagement'),
    @('传入vlsRemoteServers', 'Pass in vlsRemoteServers'),
    @('传入vlsSceneGovernance', 'Pass in vlsSceneGovernance'),
    @('传入vlsTagManagement', 'Pass in vlsTagManagement'),
    @('传入vlsTimeStrategy', 'Pass in vlsTimeStrategy'),
    @('传入vlsVideoRecord', 'Pass in vlsVideoRecord'),
    @('传入主键', 'Pass in primary key'),
    @('传入地基和', 'Pass in foundation and'),
    @('传入密码', 'Pass in password'),
    @('传入租户ID:tenantId,账号:account,密码:password', 'Pass in tenant ID: tenantId, account: account, password: password'),
    @('位置', 'Location'),
    @('位置描述', 'Location description'),
    @('低', 'Low'),
    @('低照度电子快门', 'Low-light electronic shutter'),
    @('你推荐的 曲妮妮 已通过第三轮面试', 'Qu Nini, recommended by you, has passed the third round of interviews'),
    @('你收到了 14 份新周报', 'You received 14 new weekly reports'),
    @('使用 @org.springblade.test.SignKeyGenerator 获取', 'Obtained using @org.springblade.test.SignKeyGenerator'),
    @('使用 @org.springblade.test.Sm2KeyGenerator 获取,用于国密sm2解密,前端无需配置', 'Obtained using @org.springblade.test.Sm2KeyGenerator, used for SM2 decryption, front-end configuration not required'),
    @('使用 @org.springblade.test.Sm2KeyGenerator 获取,用于国密sm2验签,需和前端保持一致', 'Obtained using @org.springblade.test.Sm2KeyGenerator, used for SM2 signature verification, needs to be consistent with the front-end')
)

foreach ($pair in $dictData) {
    $translations[$pair[0]] = $pair[1]
}

$chunkPath = "d:\work\ide\WorkSpace\vls-open-source\vls-server\Antigravity\dict_chunk_1.txt"
$lines = Get-Content -Path $chunkPath -Encoding utf8

$outputLines = [System.Collections.Generic.List[string]]::new()
$translatedCount = 0
$untranslatedCount = 0

for ($i = 0; $i -lt $lines.Count; $i++) {
    $line = $lines[$i]
    if ([string]::IsNullOrWhiteSpace($line)) {
        $outputLines.Add("")
        continue
    }
    
    $parts = $line -split " \|\|\| "
    if ($parts.Count -ge 2) {
        $key = $parts[0]
        $original = $parts[1]
        
        $translated = $translations[$original]
        if ($null -eq $translated) {
            $translated = $translations[$original.Trim()]
        }
        
        if ($null -eq $translated) {
            Write-Host "WARNING: Line $($i+1) translation not found for: '$original'"
            $translated = $original
            $untranslatedCount++
        } else {
            $translatedCount++
        }
        
        $outputLines.Add("$key ||| $original ||| $translated")
    } else {
        $outputLines.Add($line)
    }
}

$outputLines | Out-File -FilePath $chunkPath -Encoding utf8

Write-Host "Processed $($lines.Count) lines."
Write-Host "Translated: $translatedCount, Untranslated: $untranslatedCount"
