# coding: utf-8
import os

def translate():
    """
    Translates Chinese texts in dict_chunk_5.txt into English.
    """
    translation_map = {
        "智能分析请求表 分页": "Intelligent Analysis Request Table Pagination",
        "智能分析请求表 删除": "Intelligent Analysis Request Table Delete",
        "智能分析请求表 包装类,返回视图层所需的字段": "Intelligent Analysis Request Table Wrapper Class, returns fields required by the view layer",
        "智能分析请求表 实体类": "Intelligent Analysis Request Table Entity Class",
        "智能分析请求表 控制器": "Intelligent Analysis Request Table Controller",
        "智能分析请求表 数据传输对象实体类": "Intelligent Analysis Request Table Data Transfer Object Entity Class",
        "智能分析请求表 新增": "Intelligent Analysis Request Table Add",
        "智能分析请求表 新增或修改": "Intelligent Analysis Request Table Add or Modify",
        "智能分析请求表 服务实现类": "Intelligent Analysis Request Table Service Implementation Class",
        "智能分析请求表 服务类": "Intelligent Analysis Request Table Service Class",
        "智能分析请求表 视图实体类": "Intelligent Analysis Request Table View Entity Class",
        "智能分析请求表 详情": "Intelligent Analysis Request Table Details",
        "智能分析请求表接口": "Intelligent Analysis Request Table Interface",
        "智能分析请求表数据": "Intelligent Analysis Request Table Data",
        "智能分析请求表数据表": "Intelligent Analysis Request Table Data Table",
        "曝光模式": "Exposure Mode",
        "曲丽丽": "Qu Lili",
        "曲丽丽 评论了你": "Qu Lili commented on you",
        "更新label以显示数量": "Update label to display quantity",
        "更新tag_management表中的usage_count字段": "Update the usage_count field in the tag_management table",
        "更新下载次数失败：{}": "Failed to update download count: {}",
        "更新人": "Updated By",
        "更新仓库状态": "Update Repository Status",
        "更新仓库的算法数量": "Update the algorithm count of the repository",
        "更新使用次数": "Update Usage Count",
        "更新发布时间": "Update Publish Time",
        "更新图片信息": "Update Image Information",
        "更新图片信息失败: ": "Failed to update image information: ",
        "更新图片标注信息": "Update Image Annotation Information",
        "更新失败": "Update Failed",
        "更新字段": "Update Field",
        "更新容器实例状态": "Update Container Instance Status",
        "更新容器监控数据": "Update Container Monitoring Data",
        "更新成功": "Update Successful",
        "更新指定训练任务的状态": "Update the status of the specified training task",
        "更新排序": "Update Sorting",
        "更新数据集路径失败：annotationId={}": "Failed to update dataset path: annotationId={}",
        "更新时间": "Update Time",
        "更新标注 totalCount": "Update annotation totalCount",
        "更新标注实例": "Update Annotation Instance",
        "更新标注实例: instanceId={}, labelId={}": "Update annotation instance: instanceId={}, labelId={}",
        "更新标注的进度信息": "Update annotation progress information",
        "更新标注统计信息": "Update annotation statistics",
        "更新标注进度": "Update annotation progress",
        "更新标注进度：ID={}, AnnotatedCount={}": "Update annotation progress: ID={}, AnnotatedCount={}",
        "更新标签": "Update Tag",
        "更新标签 {} 的使用计数": "Update usage count of tag {}",
        "更新标签: labelId={}, name={}, color={}": "Update tag: labelId={}, name={}, color={}",
        "更新标签使用次数": "Update Tag Usage Count",
        "更新标签使用次数: labelId={}": "Update tag usage count: labelId={}",
        "更新标签信息": "Update Tag Information",
        "更新标签失败": "Failed to update tag",
        "更新标签失败: ": "Failed to update tag: ",
        "更新标签失败，ID: {}": "Failed to update tag, ID: {}",
        "更新标签排序: annotationId={}, labelIds={}": "Update tag sorting: annotationId={}, labelIds={}",
        "更新标签排序失败": "Failed to update tag sorting",
        "更新标签排序失败: ": "Failed to update tag sorting: ",
        "更新标签的使用次数": "Update tag usage count",
        "更新模型下载次数": "Update Model Download Count",
        "更新模型状态": "Update Model Status",
        "更新模型部署次数": "Update Model Deployment Count",
        "更新每个标签的使用次数": "Update the usage count of each tag",
        "更新父级和层级": "Update parent and level",
        "更新状态": "Update Status",
        "更新状态为已发布": "Update status to published",
        "更新状态为草稿": "Update status to draft",
        "更新相关仓库的算法数量": "Update algorithm count of related repositories",
        "更新算法": "Update Algorithm",
        "更新算法仓库": "Update Algorithm Repository",
        "更新算法仓库状态：ID={}, Status={}": "Update algorithm repository status: ID={}, Status={}",
        "更新算法仓库的算法数量：ID={}": "Update the algorithm count of the algorithm repository: ID={}",
        "更新算法仓库：ID={}": "Update algorithm repository: ID={}",
        "更新算法仓库：ID={}, Name={}": "Update algorithm repository: ID={}, Name={}",
        "更新算法数量": "Update Algorithm Count",
        "更新算法标注": "Update Algorithm Annotation",
        "更新算法标注：ID={}": "Update algorithm annotation: ID={}",
        "更新算法标注：ID={}, Name={}": "Update algorithm annotation: ID={}, Name={}",
        "更新算法的部署状态": "Update algorithm deployment status",
        "更新算法部署状态为部署中": "Update algorithm deployment status to deploying",
        "更新算法部署状态：ID={}, Status={}": "Update algorithm deployment status: ID={}, Status={}",
        "更新算法：ID={}": "Update algorithm: ID={}",
        "更新算法：ID={}, Name={}": "Update algorithm: ID={}, Name={}",
        "更新被删除标注的标签使用次数": "Update tag usage count of deleted annotations",
        "更新训练任务": "Update Training Task",
        "更新训练任务状态": "Update Training Task Status",
        "更新训练任务：ID={}, 数据={}": "Update training task: ID={}, data={}",
        "更新训练状态": "Update Training Status",
        "更新训练状态异常：ID={}, 错误={}": "Update training status exception: ID={}, error={}",
        "更新训练状态：ID={}, 状态={}": "Update training status: ID={}, status={}",
        "更新训练进度": "Update Training Progress",
        "更新设备信息": "Update Device Information",
        "更新设备状态": "Update Device Status",
        "更新设备配置": "Update Device Configuration",
        "更新设备配置参数": "Update Device Configuration Parameters",
        "更新设备配置失败": "Failed to update device configuration",
        "更新部署次数失败：{}": "Failed to update deployment count: {}",
        "更新部署状态": "Update Deployment Status",
        "更新配置": "Update Configuration",
        "最后修改时间": "Last Modified Time",
        "最后同步时间": "Last Sync Time",
        "最后录制时间": "Last Recording Time",
        "最后请求时间": "Last Request Time",
        "最后运行时间": "Last Run Time",
        "最后部署时间": "Last Deployment Time",
        "最大快门限制": "Maximum Shutter Limit",
        "最大线程数": "Maximum Thread Count",
        "最小快门限制": "Minimum Shutter Limit",
        "最小聚焦距离": "Minimum Focusing Distance",
        "服务ID": "Service ID",
        "服务名称": "Service Name",
        "服务器IP地址": "Server IP Address",
        "服务器名": "Server Name",
        "服务器名称": "Server Name",
        "服务器地址": "Server Address",
        "服务器环境": "Server Environment",
        "服务器连接失败": "Server Connection Failed",
        "服务器连接成功": "Server Connection Successful",
        "服务器配置": "Server Configuration",
        "服务实现类": "Service Implementation Class",
        "服务类": "Service Class",
        "未分类": "Uncategorized",
        "未开始": "Not Started",
        "未找到可用的训练服务器": "No available training server found",
        "未找到启用录制动作的事件策略": "No event policy enabling recording action was found",
        "未找到标注图片，无法生成数据集：annotationId={}": "Annotation images not found, cannot generate dataset: annotationId={}",
        "未找到要删除的图片记录: imageId={}": "Image record to delete not found: imageId={}",
        "未找到训练服务器": "Training server not found",
        "未找到训练输出目录": "Training output directory not found",
        "未找到配置算法的设备": "Devices configured with algorithms not found",
        "未找到需要检测的设备": "Devices to detect not found",
        "未指定需要检测的设备": "No device to detect is specified",
        "未标注": "Unannotated",
        "未配置事件策略，按时间策略默认启用录制": "No event policy configured, recording is enabled by default according to the time policy",
        "未配置有效的数据集路径": "No valid dataset path configured",
        "本地存储路径": "Local Storage Path",
        "朱偏右 回复了你": "Zhu Pianyou replied to you",
        "权限": "Permissions",
        "权限id": "Permission ID",
        "权限分配树形结构": "Permission Allocation Tree Structure",
        "权限标识集合": "Permission Identifier Set",
        "权限类型": "Permission Type",
        "权限类型(1:数据权限、2:接口权限)": "Permission Type (1: Data permission, 2: API permission)",
        "权限设置": "Permission Settings",
        "权限配置": "Permission Configuration",
        "权限配置菜单": "Permission Configuration Menu",
        "权限集合": "Permission Set",
        "村级区划编号": "Village-level Division Code",
        "村级名称": "Village-level Name",
        "来源": "Source",
        "构建公共标签树形结构": "Build Public Tag Tree Structure",
        "构建并返回菜单树": "Build and Return Menu Tree",
        "构建数据集 YAML 内容": "Build Dataset YAML Content",
        "构建树形结构": "Build Tree Structure",
        "构建统计结果": "Build Statistical Results",
        "构建自有标签树形结构": "Build Own Tag Tree Structure",
        "构建设备信息的完整Map，包含关联的标签信息": "Build a complete Map of device information, including associated tag information",
        "构建设备节点": "Build Device Node",
        "构建诊断命令": "Build Diagnostic Command",
        "构建路由菜单": "Build Routing Menu",
        "构建返回结构": "Build Return Structure",
        "枪机": "Bullet Camera",
        "查看详情": "View Details",
        "查询关联的标签信息": "Query Associated Tag Information",
        "查询列表": "Query List",
        "查询单条": "Query Single Record",
        "查询即时治理列表": "Query Instant Governance List",
        "查询启用的服务器配置": "Query Enabled Server Configurations",
        "查询多条(分页)": "Query Multiple Records (Pagination)",
        "查询循环治理列表（包含子循环任务）": "Query Cyclic Governance List (including sub-cyclic tasks)",
        "查询所有启用的算法仓库": "Query All Enabled Algorithm Repositories",
        "查询标注实例: annotationId={}, imageName={}": "Query annotation instance: annotationId={}, imageName={}",
        "查询标注状态统计": "Query Annotation Status Statistics",
        "查询标注类型统计": "Query Annotation Type Statistics",
        "查询标注详情": "Query Annotation Details",
        "查询标注详情：ID={}": "Query Annotation Details: ID={}",
        "查询标注进度统计": "Query Annotation Progress Statistics",
        "查询标注项目[{}]的标签列表": "Query tag list of annotation project [{}]",
        "查询标注项目的所有标注实例: annotationId={}": "Query all annotation instances of the annotation project: annotationId={}",
        "查询热门模型": "Query Popular Models",
        "查询热门模型失败": "Failed to query popular models",
        "查询热门模型失败：": "Failed to query popular models: ",
        "查询热门模型（按下载次数排序）": "Query Popular Models (sorted by download count)",
        "查询移动端即时治理列表": "Query Mobile Instant Governance List",
        "查询移动端循环治理列表（包含子循环任务）": "Query Mobile Cyclic Governance List (including sub-cyclic tasks)",
        "查询算法仓库详情": "Query Algorithm Repository Details",
        "查询算法仓库详情：ID={}": "Query Algorithm Repository Details: ID={}",
        "查询算法分类统计": "Query Algorithm Classification Statistics",
        "查询算法模型详情失败": "Failed to query algorithm model details",
        "查询算法模型详情失败：": "Failed to query algorithm model details: ",
        "查询算法类型统计": "Query Algorithm Type Statistics",
        "查询算法训练任务": "Query Algorithm Training Tasks",
        "查询算法训练任务列表": "Query Algorithm Training Task List",
        "查询算法详情": "Query Algorithm Details",
        "查询算法详情：ID={}": "Query Algorithm Details: ID={}",
        "查询训练任务详情": "Query Training Task Details",
        "查询训练任务详情：ID={}": "Query Training Task Details: ID={}",
        "查询设备在指定年份有录制记录的日期列表": "Query list of dates with recording records for the device in the specified year",
        "查询设备某一天的录制记录": "Query recording records of a device on a specific day",
        "查询设备标签失败: ": "Failed to query device tags: ",
        "查询远程服务器配置": "Query Remote Server Configurations",
        "查询远程服务器配置列表": "Query Remote Server Configuration List",
        "查询远程服务器配置详细": "Query Remote Server Configuration Details",
        "查询部署状态统计": "Query Deployment Status Statistics",
        "标注ID": "Annotation ID",
        "标注不存在": "Annotation does not exist",
        "标注不存在：ID={}": "Annotation does not exist: ID={}",
        "标注任务完成失败": "Failed to complete annotation task",
        "标注任务完成成功": "Annotation task completed successfully",
        "标注任务开始失败": "Failed to start annotation task",
        "标注任务开始成功": "Annotation task started successfully",
        "标注任务重置失败": "Failed to reset annotation task",
        "标注任务重置成功": "Annotation task reset successfully",
        "标注创建失败，名称可能已存在": "Failed to create annotation, the name may already exist",
        "标注创建成功": "Annotation created successfully",
        "标注删除失败": "Failed to delete annotation",
        "标注删除成功": "Annotation deleted successfully",
        "标注名称": "Annotation Name",
        "标注名称已存在：{}": "Annotation name already exists: {}",
        "标注图片信息表": "Annotation Image Info Table",
        "标注图片信息表 Excel实体类": "Annotation Image Info Table Excel Entity Class",
        "标注图片信息表 Mapper 接口": "Annotation Image Info Table Mapper Interface",
        "标注图片信息表 修改": "Annotation Image Info Table Update",
        "标注图片信息表 分页": "Annotation Image Info Table Pagination",
        "标注图片信息表 删除": "Annotation Image Info Table Delete",
        "标注图片信息表 包装类,返回视图层所需的字段": "Annotation Image Info Table Wrapper Class, returns fields required by the view layer",
        "标注图片信息表 实体类": "Annotation Image Info Table Entity Class",
        "标注图片信息表 控制器": "Annotation Image Info Table Controller",
        "标注图片信息表 数据传输对象实体类": "Annotation Image Info Table Data Transfer Object Entity Class",
        "标注图片信息表 新增": "Annotation Image Info Table Add",
        "标注图片信息表 新增或修改": "Annotation Image Info Table Add or Modify",
        "标注图片信息表 服务实现类": "Annotation Image Info Table Service Implementation Class",
        "标注图片信息表 服务类": "Annotation Image Info Table Service Class",
        "标注图片信息表 自定义分页": "Annotation Image Info Table Custom Pagination",
        "标注图片信息表 视图实体类": "Annotation Image Info Table View Entity Class",
        "标注图片信息表 详情": "Annotation Image Info Table Details",
        "标注图片信息表接口": "Annotation Image Info Table Interface",
        "标注图片信息表数据": "Annotation Image Info Table Data",
        "标注图片信息表数据表": "Annotation Image Info Table Data Table",
        "标注图片文件删除完成：ID={}": "Annotation image file deletion completed: ID={}",
        "标注坐标数据(JSON格式)": "Annotation Coordinate Data (JSON format)",
        "标注实例不存在": "Annotation instance does not exist",
        "标注实例保存成功，ID: {}": "Annotation instance saved successfully, ID: {}",
        "标注实例删除成功": "Annotation instance deleted successfully",
        "标注实例实体类": "Annotation Instance Entity Class",
        "标注实例实体类 Excel实体类": "Annotation Instance Entity Class Excel Entity Class",
        "标注实例实体类 Mapper 接口": "Annotation Instance Entity Class Mapper Interface",
        "标注实例实体类 修改": "Annotation Instance Entity Class Update",
        "标注实例实体类 分页": "Annotation Instance Entity Class Pagination",
        "标注实例实体类 删除": "Annotation Instance Entity Class Delete",
        "标注实例实体类 包装类,返回视图层所需的字段": "Annotation Instance Entity Class Wrapper Class, returns fields required by the view layer",
        "标注实例实体类 实体类": "Annotation Instance Entity Class Entity Class",
        "标注实例实体类 控制器": "Annotation Instance Entity Class Controller",
        "标注实例实体类 数据传输对象实体类": "Annotation Instance Entity Class Data Transfer Object Entity Class",
        "标注实例实体类 新增": "Annotation Instance Entity Class Add",
        "标注实例实体类 新增或修改": "Annotation Instance Entity Class Add or Modify",
        "标注实例实体类 服务实现类": "Annotation Instance Entity Class Service Implementation Class",
        "标注实例实体类 服务类": "Annotation Instance Entity Class Service Class",
        "标注实例实体类 自定义分页": "Annotation Instance Entity Class Custom Pagination",
        "标注实例实体类 视图实体类": "Annotation Instance Entity Class View Entity Class",
        "标注实例实体类 详情": "Annotation Instance Entity Class Details",
        "标注实例实体类接口": "Annotation Instance Entity Class Interface",
        "标注实例实体类数据": "Annotation Instance Entity Class Data",
        "标注实例实体类数据表": "Annotation Instance Entity Class Data Table",
        "标注实例更新成功": "Annotation instance updated successfully",
        "标注或数据集路径为空，跳过图片删除": "Annotation or dataset path is empty, skip image deletion",
        "标注批量删除失败": "Failed to batch delete annotations",
        "标注批量删除成功": "Batch delete annotations successfully",
        "标注数据保存到数据集失败": "Failed to save annotation data to dataset",
        "标注数据保存到数据集成功": "Annotation data saved to dataset successfully",
        "标注数据验证失败": "Failed to validate annotation data",
        "标注数据导入失败": "Failed to import annotation data",
        "标注文件上传完成：train={}, val={}": "Annotation file upload completed: train={}, val={}",
        "标注更新失败": "Failed to update annotation",
        "标注更新成功": "Annotation updated successfully",
        "标注标签实体类": "Annotation Tag Entity Class",
        "标注标签实体类 Excel实体类": "Annotation Tag Entity Class Excel Entity Class",
        "标注标签实体类 Mapper 接口": "Annotation Tag Entity Class Mapper Interface",
        "标注标签实体类 修改": "Annotation Tag Entity Class Update",
        "标注标签实体类 分页": "Annotation Tag Entity Class Pagination",
        "标注标签实体类 删除": "Annotation Tag Entity Class Delete",
        "标注标签实体类 包装类,返回视图层所需的字段": "Annotation Tag Entity Class Wrapper Class, returns fields required by the view layer",
        "标注标签实体类 实体类": "Annotation Tag Entity Class Entity Class",
        "标注标签实体类 控制器": "Annotation Tag Entity Class Controller",
        "标注标签实体类 数据传输对象实体类": "Annotation Tag Entity Class Data Transfer Object Entity Class",
        "标注标签实体类 新增": "Annotation Tag Entity Class Add",
        "标注标签实体类 新增或修改": "Annotation Tag Entity Class Add or Modify",
        "标注标签实体类 服务实现类": "Annotation Tag Entity Class Service Implementation Class",
        "标注标签实体类 服务类": "Annotation Tag Entity Class Service Class",
        "标注标签实体类 自定义分页": "Annotation Tag Entity Class Custom Pagination",
        "标注标签实体类 视图实体类": "Annotation Tag Entity Class View Entity Class",
        "标注标签实体类 详情": "Annotation Tag Entity Class Details",
        "标注标签实体类接口": "Annotation Tag Entity Class Interface",
        "标注标签实体类数据": "Annotation Tag Entity Class Data",
        "标注标签实体类数据表": "Annotation Tag Entity Class Data Table",
        "标注状态": "Annotation Status",
        "标注状态批量更新失败": "Failed to batch update annotation status",
        "标注状态批量更新成功": "Annotation status batch updated successfully",
        "标注状态枚举": "Annotation Status Enum",
        "标注状态：none-未标注,partial-部分标注,completed-完成标注": "Annotation status: none-unannotated, partial-partially annotated, completed-fully annotated",
        "标注类型": "Annotation Type",
        "标注类型枚举": "Annotation Type Enum",
        "标注类型：object_detection-物体检测,image_classification-图像分类,instance_segmentation-实例分割,semantic_segmentation-语义分割": "Annotation type: object_detection-object detection, image_classification-image classification, instance_segmentation-instance segmentation, semantic_segmentation-semantic segmentation",
        "标注类型：rect-矩形,circle-圆形,polygon-多边形": "Annotation type: rect-rectangle, circle-circle, polygon-polygon",
        "标注规则": "Annotation Rules",
        "标注进度更新失败": "Failed to update annotation progress",
        "标注进度更新成功": "Annotation progress updated successfully",
        "标注进度百分比": "Annotation progress percentage",
        "标注项目ID": "Annotation Project ID",
        "标签ID": "Tag ID",
        "标签ID列表不能为空": "Tag ID list cannot be empty",
        "标签ID索引": "Tag ID Index",
        "标签ID，关联tag_management.id": "Tag ID, associated with tag_management.id",
        "标签不存在": "Tag does not exist",
        "标签信息": "Tag Information",
        "标签创建成功，ID: {}": "Tag created successfully, ID: {}",
        "标签删除成功": "Tag deleted successfully",
        "标签名称": "Tag Name",
        "标签名称不能为空": "Tag name cannot be empty",
        "标签名称列表": "Tag name list",
        "标签名称已存在": "Tag name already exists",
        "标签图标": "Tag Icon",
        "标签大类：own-自有标签，public-公共标签": "Tag category: own-own tag, public-public tag",
        "标签描述": "Tag Description",
        "标签更新成功": "Tag updated successfully",
        "标签管理表": "Tag Management Table",
        "标签管理表 Excel实体类": "Tag Management Table Excel Entity Class",
        "标签管理表 Mapper 接口": "Tag Management Table Mapper Interface",
        "标签管理表 修改": "Tag Management Table Update",
        "标签管理表 分页": "Tag Management Table Pagination",
        "标签管理表 删除": "Tag Management Table Delete",
        "标签管理表 包装类,返回视图层所需的字段": "Tag Management Table Wrapper Class, returns fields required by the view layer",
        "标签管理表 实体类": "Tag Management Table Entity Class",
        "标签管理表 控制器": "Tag Management Table Controller",
        "标签管理表 数据传输对象实体类": "Tag Management Table Data Transfer Object Entity Class",
        "标签管理表 新增": "Tag Management Table Add",
        "标签管理表 新增或修改": "Tag Management Table Add or Modify",
        "标签管理表 服务实现类": "Tag Management Table Service Implementation Class",
        "标签管理表 服务类": "Tag Management Table Service Class",
        "标签管理表 自定义分页": "Tag Management Table Custom Pagination",
        "标签管理表 视图实体类": "Tag Management Table View Entity Class",
        "标签管理表 详情": "Tag Management Table Details",
        "标签管理表接口": "Tag Management Table Interface",
        "标签管理表数据": "Tag Management Table Data",
        "标签管理表数据表": "Tag Management Table Data Table",
        "标签类型": "Tag Type",
        "标签颜色": "Tag Color",
        "标签颜色(十六进制)": "Tag Color (hexadecimal)",
        "标签颜色不能为空": "Tag color cannot be empty",
        "标题": "Title",
        "树形结构": "Tree Structure",
        "校验Client": "Validate Client",
        "校验客户端信息": "Validate Client Information",
        "核心线程数": "Core Pool Size",
        "根据ID列表批量删除标注": "Batch delete annotations by ID list",
        "根据ID列表批量删除算法": "Batch delete algorithms by ID list",
        "根据ID列表批量删除算法仓库": "Batch delete algorithm repositories by ID list",
        "根据ID列表批量删除训练任务": "Batch delete training tasks by ID list",
        "根据ID删除标注（软删除）": "Delete annotation by ID (soft delete)",
        "根据ID删除算法仓库（软删除）": "Delete algorithm repository by ID (soft delete)",
        "根据ID删除算法（软删除）": "Delete algorithm by ID (soft delete)",
        "根据ID删除训练任务": "Delete training task by ID",
        "根据ID更新标注信息": "Update annotation information by ID",
        "根据ID更新算法仓库信息": "Update algorithm repository information by ID",
        "根据ID更新算法信息": "Update algorithm information by ID",
        "根据ID更新训练任务信息": "Update training task information by ID",
        "根据ID查询容器实例详情（包含关联信息）": "Query container instance details by ID (including associated information)",
        "根据ID查询标注详情": "Query annotation details by ID",
        "根据ID查询算法仓库详情": "Query algorithm repository details by ID",
        "根据ID查询算法模型详情": "Query algorithm model details by ID",
        "根据ID查询算法详情": "Query algorithm details by ID",
        "根据ID查询训练任务详情": "Query training task details by ID",
        "根据ID查询训练任务详情（包含关联信息）": "Query training task details by ID (including associated information)",
        "根据ID查询设备信息": "Query device information by ID",
        "根据ID获取图片详情": "Get image details by ID",
        "根据ID获取标注详细信息": "Get detailed annotation information by ID",
        "根据ID获取算法仓库详细信息": "Get detailed algorithm repository information by ID",
        "根据ID获取算法详细信息": "Get detailed algorithm information by ID",
        "根据ID获取训练任务详细信息": "Get detailed training task information by ID",
        "根据IP地址查询设备": "Query device by IP address",
        "根据code获取枚举": "Get enum by code",
        "根据id取消智能分析申请": "Cancel intelligent analysis application by ID",
        "根据不同用户类型调用对应的接口返回数据，用户可自行拓展": "Call corresponding interface to return data based on different user types, users can extend by themselves",
        "根据仓库ID查询算法列表": "Query algorithm list by repository ID",
        "根据仓库ID查询算法列表：{}": "Query algorithm list by repository ID: {}",
        "根据仓库类型获取算法仓库列表": "Get algorithm repository list by repository type",
        "根据位置查询设备": "Query device by location",
        "根据位置获取设备列表": "Get device list by location",
        "根据分类查询算法列表": "Query algorithm list by category",
        "根据分类查询算法列表：{}": "Query algorithm list by category: {}",
        "根据分类类型获取标签": "Get tags by category type",
        "根据创建人查询模型数量": "Query model count by creator",
        "根据创建人查询模型数量失败": "Failed to query model count by creator",
        "根据创建人查询模型数量失败：": "Failed to query model count by creator: ",
        "根据名称搜索标签": "Search tags by name",
        "根据名称查询场景治理信息": "Query scene governance information by name",
        "根据域名查询信息": "Query information by domain name",
        "根据多个标签查询设备（交集 - 必须同时包含所有标签）": "Query devices by multiple tags (intersection - must contain all tags simultaneously)",
        "根据多个标签查询设备（交集）": "Query devices by multiple tags (intersection)",
        "根据多个标签查询设备（并集 - 包含任意一个标签）": "Query devices by multiple tags (union - contains any one tag)",
        "根据多个标签查询设备（并集）": "Query devices by multiple tags (union)",
    }

    input_path = r"d:\work\ide\WorkSpace\vls-open-source\vls-server\Antigravity\dict_chunk_5.txt"
    output_path = input_path

    # Read existing file content
    with open(input_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    result_lines = []
    mismatch_count = 0
    for idx, line in enumerate(lines, 1):
        line = line.strip('\r\n')
        if not line:
            result_lines.append("")
            continue
        parts = line.split(" ||| ")
        if len(parts) >= 2:
            key = parts[0]
            orig = parts[1]
            if orig in translation_map:
                trans = translation_map[orig]
                result_lines.append(f"{key} ||| {orig} ||| {trans}")
            else:
                mismatch_count += 1
                result_lines.append(f"{key} ||| {orig} ||| ")
                print(f"Mismatch at line {idx}: {orig}")
        else:
            result_lines.append(line)

    # Write output back
    with open(output_path, 'w', encoding='utf-8') as f:
        for r_line in result_lines:
            f.write(r_line + '\n')

    print(f"Total lines read: {len(lines)}")
    print(f"Total lines written: {len(result_lines)}")
    print(f"Mismatch count: {mismatch_count}")

if __name__ == "__main__":
    translate()
