# -*- coding: utf-8 -*-
import base64
import os
import sys

chunk_path = r"d:\work\ide\WorkSpace\vls-open-source\vls-server\Antigravity\dict_chunk_0.txt"

# Complete dictionary of translations from original Chinese text to English.
translation_map = {
    " 个实例": " instances",
    " 个目标": " targets",
    " 个结果": " results",
    " 保存失败": " Save failed",
    " 分割到 ": " Split to ",
    " 分类到 ": " Classified to ",
    " 台设备": " devices",
    " 处理异常: ": " Process exception: ",
    " 完成语义分割": " Complete semantic segmentation",
    " 已发布，不能删除": " Published, cannot be deleted",
    " 张人脸": " faces",
    " 标注数据集\\n": " Annotation dataset\\n",
    " 检测到 ": " Detected ",
    " 检测到姿态": " Detected posture",
    " 状态不允许发布": " Status does not allow publishing",
    " 验证失败": " Verification failed",
    "# - images/train/ (训练图片)\\n": "# - images/train/ (Training images)\\n",
    "# - images/val/ (验证图片)\\n": "# - images/val/ (Validation images)\\n",
    "# - labels/train/ (训练标注)\\n": "# - labels/train/ (Training annotations)\\n",
    "# - labels/val/ (验证标注)\\n": "# - labels/val/ (Validation annotations)\\n",
    "# YOLO数据集配置文件\\n": "# YOLO dataset configuration file\\n",
    "# 创建时间: ": "# Creation time: ",
    "# 实际训练需要以下目录结构：\\n": "# Actual training requires the following directory structure:\\n",
    "# 数据集信息\\n": "# Dataset information\\n",
    "# 数据集路径配置\\n": "# Dataset path configuration\\n",
    "# 标注名称: ": "# Annotation name: ",
    "# 注意：此配置文件仅包含基本设置\\n": "# Note: This configuration file only contains basic settings\\n",
    "# 类别配置\\n": "# Class configuration\\n",
    "#blade配置 \\n": "#blade configuration \\n",
    "#blade配置\\n": "#blade configuration\\n",
    "#redis 单机环境配置": "#redis standalone environment configuration",
    "#redis 集群环境配置": "#redis cluster environment configuration",
    '* Copyright (c) 2018-2099, Chill Zhuang 庄骞 (bladejava@qq.com).\r\n * <p>\r\n * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE 3.0;\r\n * you may not use this file except in compliance with the License.\r\n * You may obtain a copy of the License at\r\n * <p>\r\n * http://www.gnu.org/licenses/lgpl.html\r\n * <p>\r\n * Unless required by applicable law or agreed to in writing, software\r\n * distributed under the License is distributed on an "AS IS" BASIS,\r\n * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\r\n * See the License for the specific language governing permissions and\r\n * limitations under the License. *': '* Copyright (c) 2018-2099, Chill Zhuang 庄骞 (bladejava@qq.com).\r\n * <p>\r\n * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE 3.0;\r\n * you may not use this file except in compliance with the License.\r\n * You may obtain a copy of the License at\r\n * <p>\r\n * http://www.gnu.org/licenses/lgpl.html\r\n * <p>\r\n * Unless required by applicable law or agreed to in writing, software\r\n * distributed under the License is distributed on an "AS IS" BASIS,\r\n * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\r\n * See the License for the specific language governing permissions and\r\n * limitations under the License. *',
    '* Copyright (c) 2018-2099, Chill Zhuang 庄骞 (bladejava@qq.com).\r\n * <p>\r\n * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE 3.0;\r\n * you may not use this file except in compliance with the License.\r\n * You may obtain a copy of the License at\r\n * <p>\r\n * http://www.gnu.org/licenses/lgpl.html\r\n * <p>\r\n * Unless required by applicable law or agreed to in writing, software\r\n * distributed under the License is distributed on an "AS IS" BASIS,\r\n * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\r\n * See the License for the specific language governing permissions and\r\n * limitations under the License.\r\n *': '* Copyright (c) 2018-2099, Chill Zhuang 庄骞 (bladejava@qq.com).\r\n * <p>\r\n * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE 3.0;\r\n * you may not use this file except in compliance with the License.\r\n * You may obtain a copy of the License at\r\n * <p>\r\n * http://www.gnu.org/licenses/lgpl.html\r\n * <p>\r\n * Unless required by applicable law or agreed to in writing, software\r\n * distributed under the License is distributed on an "AS IS" BASIS,\r\n * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\r\n * See the License for the specific language governing permissions and\r\n * limitations under the License.\r\n *',
    ", 速度: ": ", speed: ",
    "//saber配置\\n": "//saber configuration\\n",
    "1-是，0-否": "1-Yes, 0-No",
    "1. 查询该图片的所有标注实例": "1. Query all annotation instances of the image",
    "10分钟无活动自动清理": "Automatically clean up after 10 minutes of inactivity",
    "1小时": "1 hour",
    "2. 统计每个标签的使用次数，用于后续更新标签计数": "2. Count the usage times of each label for subsequent updates of label count",
    "24小时制": "24-hour format",
    "3. 删除所有标注实例": "3. Delete all annotation instances",
    "30秒超时": "30 seconds timeout",
    "4. 删除图片记录（annotation_image表）": "4. Delete image record (annotation_image table)",
    "5. 更新标签使用计数（annotation_label表）": "5. Update label usage count (annotation_label table)",
    "=== 开始训练任务 ===": "=== Start training task ===",
    "=========== blade.token.sign-key 配置如下 ==============": "=========== blade.token.sign-key configuration is as follows ==============",
    "============== saber website.js 配置如下 ===============": "============== saber website.js configuration is as follows ===============",
    "============== 密码:[admin] 加密流程如下 ================": "============== Password:[admin] encryption workflow is as follows ================",
    "================ blade.auth 配置如下 =================": "================ blade.auth configuration is as follows =================",
    "==================== 设备标签相关接口 ====================": "==================== Device tag related interfaces ====================",
    "@author 刘鑫": "@author Liu Xin",
    "@param account    账号": "@param account    account",
    "@param algorithm 算法信息": "@param algorithm algorithm information",
    "@param algorithmId 算法ID": "@param algorithmId algorithm ID",
    "@param algorithmTraining 算法训练任务": "@param algorithmTraining algorithm training task",
    "@param allTags 所有标签": "@param allTags all tags",
    "@param annotatedCount 已标注数量": "@param annotatedCount annotated quantity",
    "@param annotation 标注信息": "@param annotation annotation information",
    "@param annotationData JSON格式的标注数据": "@param annotationData annotation data in JSON format",
    "@param annotationData 标注数据（JSON格式）": "@param annotationData annotation data (JSON format)",
    "@param annotationId   标注ID": "@param annotationId   annotation ID",
    "@param annotationId 标注ID": "@param annotationId annotation ID",
    "@param annotationId 标注项目ID": "@param annotationId annotation project ID",
    "@param annotationImages 图片信息列表": "@param annotationImages image information list",
    "@param annotationName 标注名称": "@param annotationName annotation name",
    "@param annotationName 标注名称（模糊查询）": "@param annotationName annotation name (fuzzy query)",
    "@param annotationStatus 新标注状态": "@param annotationStatus new annotation status",
    "@param annotationStatus 标注状态": "@param annotationStatus annotation status",
    "@param annotationType 标注类型": "@param annotationType annotation type",
    "@param annotations 标注实例列表": "@param annotations annotation instances list",
    "@param apiScopeIds  接口权限id集合": "@param apiScopeIds  API permission ID set",
    "@param bladeRedis Redis缓存": "@param bladeRedis Redis cache",
    "@param bucketName 存储桶名称": "@param bucketName bucket name",
    "@param cacheKey      缓存key": "@param cacheKey      cache key",
    "@param cacheKeyValue 缓存key值": "@param cacheKeyValue cache key value",
    "@param category 算法分类": "@param category algorithm category",
    "@param category 算法类型": "@param category algorithm type",
    "@param categoryType 分类类型(own-自有, public-公共)": "@param categoryType category type (own-owned, public-public)",
    "@param categoryType 标签大类": "@param categoryType label major category",
    "@param categoryType 标签类型（own/public）": "@param categoryType label type (own/public)",
    "@param clientId     客户端id": "@param clientId     client ID",
    "@param clientId 客户端id": "@param clientId client ID",
    "@param clientSecret 客户端密钥": "@param clientSecret client secret",
    "@param code    字典编号": "@param code    dict code",
    "@param code 字典编号": "@param code dict code",
    "@param code 状态码": "@param code status code",
    "@param color 标签颜色": "@param color label color",
    "@param command PTZ命令": "@param command PTZ command",
    "@param config 配置参数": "@param config configuration parameters",
    "@param containerId 容器ID": "@param containerId container ID",
    "@param count 使用次数": "@param count usage count",
    "@param cpuUsage CPU使用率": "@param cpuUsage CPU usage",
    "@param createDTO 创建参数": "@param createDTO creation parameters",
    "@param createdBy 创建人": "@param createdBy creator",
    "@param createdBy 创建人ID": "@param createdBy creator ID",
    "@param createdTimeBegin 创建时间范围开始": "@param createdTimeBegin creation time range start",
    "@param createdTimeEnd 创建时间范围结束": "@param createdTimeEnd creation time range end",
    "@param dataPath 数据路径": "@param dataPath data path",
    "@param dataScopeIds 数据权限id集合": "@param dataScopeIds data scope ID set",
    "@param datasetId 数据集ID": "@param datasetId dataset ID",
    "@param datasetPath 数据集路径": "@param datasetPath dataset path",
    "@param deployStatus 新部署状态": "@param deployStatus new deployment status",
    "@param deployStatus 部署状态": "@param deployStatus deployment status",
    "@param description 标签描述": "@param description label description",
    "@param destBucketName 目标存储桶名称": "@param destBucketName destination bucket name",
    "@param destFileName   目标存储桶对象名称": "@param destFileName   destination object name",
    "@param deviceId 设备ID": "@param deviceId device ID",
    "@param deviceId 设备编号": "@param deviceId device code",
    "@param deviceIds 设备ID列表": "@param deviceIds device ID list",
    "@param deviceIds 设备ID列表，为空时导出所有设备": "@param deviceIds device ID list; if empty, export all devices",
    "@param deviceInfo 设备信息": "@param deviceInfo device information",
    "@param deviceList 设备列表": "@param deviceList device list",
    "@param deviceName 设备名称或设备ID": "@param deviceName device name or device ID",
    "@param deviceTagMap 设备ID -> 标签ID列表的映射": "@param deviceTagMap mapping of device ID -> label ID list",
    "@param deviceType 设备类型": "@param deviceType device type",
    "@param dictKey 字典序号": "@param dictKey dict key",
    "@param directory 目录": "@param directory directory",
    "@param domain 域名": "@param domain domain",
    "@param endTime 结束时间": "@param endTime end time",
    "@param epochCurrent 当前轮次": "@param epochCurrent current epoch",
    "@param errorMessage 错误信息": "@param errorMessage error message",
    "@param excludeId 排除的ID（更新时使用）": "@param excludeId excluded ID (used when updating)",
    "@param excludeId 排除的ID（用于编辑时验证）": "@param excludeId excluded ID (used for validation during editing)",
    "@param file     文件": "@param file     file",
    "@param file 文件": "@param file file",
    "@param fileName       存储桶对象名称": "@param fileName       bucket object name",
    "@param fileName 存储桶对象名称": "@param fileName bucket object name",
    "@param fileName 文件名": "@param fileName file name",
    "@param fileNames 存储桶对象名称集合": "@param fileNames bucket object name collection",
    "@param filename 文件名": "@param filename file name",
    "@param gpuUsage GPU使用率": "@param gpuUsage GPU usage",
    "@param grantType 授权类型": "@param grantType grant type",
    "@param healthStatus 健康状态": "@param healthStatus health status",
    "@param host     服务器地址": "@param host     server address",
    "@param host 服务器地址": "@param host server address",
    "@param id     设备ID": "@param id     device ID",
    "@param id 仓库ID": "@param id repository ID",
    "@param id 容器实例ID": "@param id container instance ID",
    "@param id 标注ID": "@param id annotation ID",
    "@param id 模型ID": "@param id model ID",
    "@param id 算法ID": "@param id algorithm ID",
    "@param id 算法训练任务主键": "@param id algorithm training task primary key",
    "@param id 训练任务ID": "@param id training task ID",
    "@param id 设备ID": "@param id device ID",
    "@param id 远程服务器配置主键": "@param id remote server configuration primary key",
    "@param ids    设备ID列表": "@param ids    device ID list",
    "@param ids 仓库ID列表": "@param ids repository ID list",
    "@param ids 任务ID列表": "@param ids task ID list",
    "@param ids 容器实例ID列表": "@param ids container instance ID list",
    "@param ids 标注ID列表": "@param ids annotation ID list",
    "@param ids 模型ID列表": "@param ids model ID list",
    "@param ids 算法ID列表": "@param ids algorithm ID list",
    "@param ids 设备ID列表": "@param ids device ID list",
    "@param ids 需要删除的算法训练任务主键": "@param ids primary keys of the algorithm training tasks to be deleted",
    "@param ids 需要删除的算法训练任务主键集合": "@param ids set of primary keys of the algorithm training tasks to be deleted",
    "@param ids 需要删除的远程服务器配置主键": "@param ids primary keys of remote server configurations to be deleted",
    "@param ids 需要删除的远程服务器配置主键集合": "@param ids set of primary keys of remote server configurations to be deleted",
    "@param imageId 图片ID": "@param imageId image ID",
    "@param imageId 图片id": "@param imageId image ID",
    "@param imageInstances 标注数据": "@param imageInstances annotation data",
    "@param imageName    图片名称": "@param imageName    image name",
    "@param imageName 图片名称": "@param imageName image name",
    "@param increment 增加的次数": "@param increment increased count",
    "@param instanceId 实例ID": "@param instanceId instance ID",
    "@param instanceIds 实例ID列表": "@param instanceIds instance ID list",
    "@param instanceName 实例名称": "@param instanceName instance name",
    "@param instanceStatus 实例状态": "@param instanceStatus instance status",
    "@param ipAddress IP地址": "@param ipAddress IP address",
    "@param isActive 是否启用": "@param isActive whether enabled",
    "@param keyword      搜索关键词（可选）": "@param keyword      search keyword (optional)",
    "@param keyword 搜索关键字": "@param keyword search keyword",
    "@param keyword 搜索关键词": "@param keyword search keyword",
    "@param labelId     标签ID": "@param labelId     label ID",
    "@param labelId 标签ID": "@param labelId label ID",
    "@param labelIds 标签ID列表（按排序顺序）": "@param labelIds label ID list (in sort order)",
    "@param level 标签层级": "@param level label level",
    "@param level 标签层级（1/2）": "@param level label level (1/2)",
    "@param limit 限制数量": "@param limit limit quantity",
    "@param memoryUsage 内存使用率": "@param memoryUsage memory usage",
    "@param menuIds      菜单id集合": "@param menuIds      menu ID set",
    "@param menuIds    菜单id集合": "@param menuIds    menu ID set",
    "@param modelName 模型名称": "@param modelName model name",
    "@param name 仓库名称（模糊查询）": "@param name repository name (fuzzy query)",
    "@param name 场景名称": "@param name scene name",
    "@param name 标签名称": "@param name label name",
    "@param name 算法名称（模糊查询）": "@param name algorithm name (fuzzy query)",
    "@param order 排序方式": "@param order sort order",
    "@param orderBy 排序字段": "@param orderBy sort field",
    "@param page             分页参数": "@param page             pagination parameters",
    "@param page          分页参数": "@param page          pagination parameters",
    "@param page       分页对象": "@param page       pagination object",
    "@param page 分页参数": "@param page pagination parameters",
    "@param page 分页对象": "@param page pagination object",
    "@param params 参数": "@param params parameters",
    "@param parentId  父级ID": "@param parentId  parent ID",
    "@param parentId 父级ID": "@param parentId parent ID",
    "@param parentMap 父级分组": "@param parentMap parent grouping",
    "@param password 密码": "@param password password",
    "@param path     数据集路径": "@param path     dataset path",
    "@param path 数据集路径": "@param path dataset path",
    "@param path 目录路径": "@param path directory path",
    "@param position 位置": "@param position position",
    "@param position 设备位置": "@param position device position",
    "@param privateKey  私钥": "@param privateKey  private key",
    "@param profile 环境变量": "@param profile environment variable",
    "@param progress 进度百分比": "@param progress progress percentage",
    "@param publicKey   公钥": "@param publicKey   public key",
    "@param queryWrapper 查询条件": "@param queryWrapper query conditions",
    "@param rawPassword 请求时提交的原密码": "@param rawPassword original password submitted during request",
    "@param recordDate 日期": "@param recordDate date",
    "@param remoteServer 远程服务器配置": "@param remoteServer remote server configuration",
    "@param repository 算法仓库信息": "@param repository algorithm repository information",
    "@param repositoryId 仓库ID": "@param repositoryId repository ID",
    "@param repositoryType 仓库类型": "@param repositoryType repository type",
    "@param requestBody  请求体": "@param requestBody  request body",
    "@param requestBody  请求体（包含labelIds数组）": "@param requestBody  request body (including labelIds array)",
    "@param requestBody 请求体": "@param requestBody request body",
    "@param response HTTP响应对象": "@param response HTTP response object",
    "@param roleIds      角色id集合": "@param roleIds      role ID set",
    "@param sftp        SFTP通道": "@param sftp        SFTP channel",
    "@param sftp SFTP通道": "@param sftp SFTP channel",
    "@param size 文件大小（字节）": "@param size file size (bytes)",
    "@param sourceDeviceId 源设备ID": "@param sourceDeviceId source device ID",
    "@param startTime 启动时间": "@param startTime start time",
    "@param startTime 开始时间": "@param startTime start time",
    "@param startTime 起始时间": "@param startTime start time",
    "@param startTimeBegin 开始时间范围开始": "@param startTimeBegin start time range start",
    "@param startTimeEnd 开始时间范围结束": "@param startTimeEnd start time range end",
    "@param status     设备状态": "@param status     device status",
    "@param status    状态": "@param status    status",
    "@param status 场景状态": "@param status scene status",
    "@param status 新状态": "@param status new status",
    "@param status 状态": "@param status status",
    "@param status 设备状态": "@param status device status",
    "@param stopTime 停止时间": "@param stopTime stop time",
    "@param tag        设备标签（实际对应device_type字段）": "@param tag        device tag (actually corresponds to the device_type field)",
    "@param tag 标签": "@param tag label",
    "@param tagId     标签ID": "@param tagId     label ID",
    "@param tagId 标签ID": "@param tagId label ID",
    "@param tagIds 原始标签ID列表": "@param tagIds original label ID list",
    "@param tagIds 标签ID列表": "@param tagIds label ID list",
    "@param tagManagement 标签信息": "@param tagManagement label information",
    "@param tagName   标签名称": "@param tagName   label name",
    "@param tagName 标签名称": "@param tagName label name",
    "@param tagType 标签类型": "@param tagType label type",
    "@param tagType 标签类型(own-自有, public-公共)": "@param tagType label type (own-owned, public-public)",
    "@param targetDeviceIds 目标设备ID列表": "@param targetDeviceIds target device ID list",
    "@param targetParentId 目标父级ID": "@param targetParentId target parent ID",
    "@param targetPosition 目标位置": "@param targetPosition target position",
    "@param taskName 任务名称": "@param taskName task name",
    "@param tenantId      租户编号": "@param tenantId      tenant code",
    "@param tenantId   租户ID": "@param tenantId   tenant ID",
    "@param timeStrategy 时间策略": "@param timeStrategy time strategy",
    "@param tokenParameter 授权参数": "@param tokenParameter authorization parameters",
    "@param topMenuIds 顶部菜单id集合": "@param topMenuIds top menu ID set",
    "@param trainStatus 训练状态": "@param trainStatus training status",
    "@param trainType 训练类型": "@param trainType training type",
    "@param trainingId 训练任务ID": "@param trainingId training task ID",
    "@param usageCount 使用次数": "@param usageCount usage count",
    "@param userInfo 用户信息": "@param userInfo user information",
    "@param username 用户名": "@param username username",
    "@param val 字符串值": "@param val string value",
    "@param version 版本": "@param version version",
    "@param vlsAlgorithm 查询参数": "@param vlsAlgorithm query parameters",
    "@param vlsAlgorithmAnnotation 查询参数": "@param vlsAlgorithmAnnotation query parameters",
    "@param vlsAlgorithmModel 查询参数": "@param vlsAlgorithmModel query parameters",
    "@param vlsAlgorithmOrchestration 查询参数": "@param vlsAlgorithmOrchestration query parameters",
    "@param vlsAlgorithmRepository 查询参数": "@param vlsAlgorithmRepository query parameters",
    "@param vlsAlgorithmTraining 查询参数": "@param vlsAlgorithmTraining query parameters",
    "@param vlsAnalysisRequest 查询参数": "@param vlsAnalysisRequest query parameters",
    "@param vlsAnnotationImage 查询参数": "@param vlsAnnotationImage query parameters",
    "@param vlsAnnotationInstance 查询参数": "@param vlsAnnotationInstance query parameters",
    "@param vlsAnnotationLabel 查询参数": "@param vlsAnnotationLabel query parameters",
    "@param vlsContainerInstance 查询参数": "@param vlsContainerInstance query parameters",
    "@param vlsDeviceInfo 查询参数": "@param vlsDeviceInfo query parameters",
    "@param vlsDeviceTagRelation 查询参数": "@param vlsDeviceTagRelation query parameters",
    "@param vlsEventManagement 查询参数": "@param vlsEventManagement query parameters",
    "@param vlsRemoteServers 查询参数": "@param vlsRemoteServers query parameters",
    "@param vlsSceneGovernance 查询参数": "@param vlsSceneGovernance query parameters",
    "@param vlsTagManagement 查询参数": "@param vlsTagManagement query parameters",
    "@param vlsTimeStrategy 查询参数": "@param vlsTimeStrategy query parameters",
    "@param vlsVideoRecord 查询参数": "@param vlsVideoRecord query parameters",
    "@param year 年份（为空时不限制）": "@param year year (no limit if empty)",
    "@return 仓库总数": "@return total number of repositories",
    "@return 使用次数": "@return usage count",
    "@return 使用统计信息": "@return usage statistics",
    "@return 保存的标注实例": "@return saved annotation instances",
    "@return 保存结果": "@return save result",
    "@return 分类统计信息": "@return classification statistics",
    "@return 分页结果": "@return pagination results",
    "@return 创建成功的标签": "@return successfully created label",
    "@return 创建成功的模型": "@return successfully created model",
    "@return 创建的标签": "@return created label",
    "@return 删除数量": "@return deleted quantity",
    "@return 删除结果": "@return deletion result",
    "@return 删除行数": "@return number of deleted rows",
    "@return 刷新结果": "@return refresh result",
    "@return 启用数量": "@return enabled quantity",
    "@return 启用的算法仓库列表": "@return list of enabled algorithm repositories",
    "@return 品牌列表": "@return brand list",
    "@return 回放记录列表": "@return playback record list",
    "@return 场景治理信息": "@return scene governance information",
    "@return 场景治理列表": "@return scene governance list",
    "@return 子标签列表": "@return sub-label list",
    "@return 子节点列表": "@return child node list",
    "@return 存在的数量": "@return existing quantity",
    "@return 容器实例": "@return container instance",
    "@return 容器实例列表": "@return container instance list",
    "@return 容器实例详情": "@return container instance details",
    "@return 导入结果": "@return import result",
    "@return 导出 data": "@return exported data",
    "@return 导出数据": "@return exported data",
    "@return 异常状态的容器实例列表": "@return list of container instances in abnormal state",
    "@return 录制记录列表": "@return recording list",
    "@return 影响行数": "@return affected rows",
    "@return 总大小（字节）": "@return total size (bytes)",
    "@return 总数": "@return total count",
    "@return 成功设置的设备数量": "@return number of successfully configured devices",
    "@return 控制结果": "@return control result",
    "@return 插入数量": "@return inserted quantity",
    "@return 数据集文件内容": "@return dataset file content",
    "@return 数据集文件名": "@return dataset file name",
    "@return 数量": "@return quantity",
    "@return 文件内容": "@return file content",
    "@return 文件列表": "@return file list",
    "@return 文件响应信息": "@return file response information",
    "@return 日期列表": "@return date list",
    "@return 时间策略": "@return time strategy",
    "@return 是否为\"否\"": "@return whether it is \"No\"",
    "@return 是否为\"是\"": "@return whether it is \"Yes\"",
    "@return 是否为图片文件": "@return whether it is an image file",
    "@return 是否保存成功": "@return whether saved successfully",
    "@return 是否停止成功": "@return whether stopped successfully",
    "@return 是否删除成功": "@return whether deleted successfully",
    "@return 是否启动成功": "@return whether started successfully",
    "@return 是否存在": "@return whether exists",
    "@return 是否成功": "@return whether successful",
    "@return 是否操作成功": "@return whether operated successfully",
    "@return 是否更新成功": "@return whether updated successfully",
    "@return 是否移动成功": "@return whether moved successfully",
    "@return 是否连接成功": "@return whether connected successfully",
    "@return 是否重启成功": "@return whether restarted successfully",
    "@return 是否重复": "@return whether duplicated",
    "@return 更新后的标注实例": "@return updated annotation instances",
    "@return 更新后的标签": "@return updated label",
    "@return 更新成功的标签": "@return successfully updated label",
    "@return 更新数量": "@return updated quantity",
    "@return 更新结果": "@return update result",
    "@return 更新行数": "@return number of updated rows",
    "@return 最大排序号": "@return maximum sort number",
    "@return 有效的标签ID列表": "@return valid label ID list",
    "@return 枚举对象": "@return enum object",
    "@return 标注列表": "@return annotation list",
    "@return 标注实例列表": "@return annotation instances list",
    "@return 标注工作量统计信息": "@return annotation workload statistics",
    "@return 标注状态": "@return annotation status",
    "@return 标注状态统计信息": "@return annotation status statistics",
    "@return 标注类型统计信息": "@return annotation type statistics",
    "@return 标注进度统计信息": "@return annotation progress statistics",
    "@return 标签ID列表": "@return label ID list",
    "@return 标签使用统计": "@return label usage statistics",
    "@return 标签信息列表": "@return label information list",
    "@return 标签列表": "@return label list",
    "@return 标签树": "@return label tree",
    "@return 标签详细信息": "@return label details",
    "@return 树形结构": "@return tree structure",
    "@return 根级标签列表": "@return root level label list",
    "@return 格式化后的文件大小": "@return formatted file size",
    "@return 模型列表": "@return model list",
    "@return 模型数量": "@return model quantity",
    "@return 模型文件路径": "@return model file path",
    "@return 正在训练的任务列表": "@return list of training tasks",
    "@return 禁用数量": "@return disabled quantity",
    "@return 等待中的任务列表": "@return list of waiting tasks",
    "@return 算法仓库列表": "@return algorithm repository list",
    "@return 算法列表": "@return algorithm list",
    "@return 算法数量": "@return algorithm quantity",
    "@return 算法模型": "@return algorithm model",
    "@return 算法模型列表": "@return algorithm model list",
    "@return 算法训练任务": "@return algorithm training task",
    "@return 算法训练任务集合": "@return algorithm training task collection",
    "@return 类型统计信息": "@return type statistics",
    "@return 结果": "@return result",
    "@return 统计信息": "@return statistics",
    "@return 统计结果": "@return statistical results",
    "@return 视频流信息": "@return video stream information",
    "@return 解密后的密码": "@return decrypted password",
    "@return 解析后的数据": "@return parsed data",
    "@return 训练任务列表": "@return training task list",
    "@return 训练任务详情": "@return training task details",
    "@return 设备ID列表": "@return device ID list",
    "@return 设备信息": "@return device information",
    "@return 设备信息分页列表": "@return paginated list of device information",
    "@return 设备信息列表": "@return device information list",
    "@return 设备列表": "@return device list",
    "@return 设备数量": "@return device quantity",
    "@return 设备标签关联列表": "@return device tag relation list",
    "@return 设备类型列表": "@return device type list",
    "@return 评估结果": "@return evaluation results",
    "@return 转换后的 Long 值，如果转换失败则返回 null": "@return converted Long value, or null if conversion fails"
}

if __name__ == '__main__':
    with open(chunk_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    print(f"Total lines read: {len(lines)}")

    translated_lines = []
    missing = []

    for idx, line in enumerate(lines):
        # Strip trailing newlines for processing
        stripped = line.rstrip('\r\n')
        if not stripped.strip():
            # Keep blank lines exactly as they are
            translated_lines.append(line)
            continue
            
        # Split by ' ||| '
        parts = stripped.split(" ||| ")
        if len(parts) < 2:
            translated_lines.append(line)
            continue
            
        b64_key = parts[0]
        orig_text_in_file = parts[1]
        
        # Decode the key to match exactly
        try:
            decoded_text = base64.b64decode(b64_key).decode('utf-8')
        except Exception as e:
            print(f"Error decoding base64 on line {idx+1}: {e}")
            raise e
            
        trans_text = translation_map.get(decoded_text, None)
        if trans_text is None:
            # Check if already English
            has_chinese = any('\u4e00' <= char <= '\u9fff' for char in decoded_text)
            if not has_chinese:
                trans_text = decoded_text
            else:
                missing.append((idx + 1, decoded_text))
        
        if trans_text is not None:
            # Replace actual newlines in translation with literal \r\n and \n to keep single-line entries
            trans_text = trans_text.replace('\r\n', '\\r\\n').replace('\n', '\\n')
                
        # Preserve original newline ending of this line
        line_ending = ""
        if line.endswith("\r\n"):
            line_ending = "\r\n"
        elif line.endswith("\n"):
            line_ending = "\n"
            
        # Reconstruct the line: BASE64_KEY ||| ORIGINAL_TEXT ||| TRANSLATED_TEXT
        new_line = f"{b64_key} ||| {orig_text_in_file} ||| {trans_text}{line_ending}"
        translated_lines.append(new_line)

    if missing:
        print(f"Found {len(missing)} missing translations:")
        for num, text in missing:
            print(f"Line {num}: {repr(text)}")
        sys.exit(1)

    # Verification
    if len(translated_lines) != len(lines):
        raise ValueError("Lines count mismatch after translation!")

    for l_orig, l_trans in zip(lines, translated_lines):
        if not l_orig.strip():
            continue
        k_orig = l_orig.split(" ||| ")[0]
        k_trans = l_trans.split(" ||| ")[0]
        if k_orig != k_trans:
            raise ValueError(f"Key mismatch: {k_orig} vs {k_trans}")

    # Write back
    with open(chunk_path, "w", encoding="utf-8") as f:
        f.writelines(translated_lines)

    print("Translation completed successfully!")
